### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by stj** [Joowani/python-arango#1]
Hi Joowani,

I am currently looking for a tornado arango async adapter and saw that you have async on your feature list. I might fork you repo and write that part myself. Please let me know if you have any thoughts about async support in your code already that I should consider.

So far I only briefly went over your code but it might be enough to write a async client class.
Cheers

**Comment by Joowani** [comment]
Hello stj,

Yes feel free to fork! Unfortunately I haven't had the time myself to look
further into the async support so I don't have much to share with you.

Regards,
Joohwan
