### ISSUE TITLE
How to display error messages?

### ISSUE THREAD

**Issue by eldertrevisan** [joowani/python-arango#10]
How to display error messages? For example, if a database or a collection exists.

**Comment by joowani** [comment]
Hi eldertrevisan,

For database and collection you can catch KeyError or arango.exceptions.NotFoundError:
```python
try:
    a.database('missing_database')
except KeyError:
    print('db missing!')
```    

For any request related errors you can do the following:
```python
from arango.exceptions import RequestError
try:
    # something
except RequestError as err:
    print(err.message)
    print(err.error_code)
    print(err.http_code)
    print(err.url)
    print(err.method)
```

I am planning to improve the exceptions in the future

Jay

**Comment by joowani** [comment]
Hi eldertrevisan,

In the next release, ALL python-arango exceptions will subclass from ArangoError. I will also put up a documentation page soon so you have something to refer to. For now I will close this issue. Thanks.
