### ISSUE TITLE
Deleting vertex collections of a graph does not work

### ISSUE THREAD

**Issue by agentS** [joowani/python-arango#101]
Hi,

First of all thank you for your efforts and your great library!

I am using the following code to delete a collection, which may either be an edge definition or a vertex collection.

```python
class ArangoDbManager(AbstractManager):
    """..."""

    def delete_collection(self, name: str) -> bool:
        """Delete a collection identified by name"""

        print(name)
        if self.graph:
            if self.graph.has_edge_definition(name):
                self.graph.delete_edge_definition(name, purge=True)
            elif self.graph.has_vertex_collection(name):
                self.graph.delete_vertex_collection(name, purge=True)
                print(self.graph.vertex_collections())
        #return self.database.delete_collection(name) # if the vertex collection is not deleted from the graph, this statement causes the entire graph to become unusable
```

However, even after executing `graph.delete_vertex_collection(name, purge=True)` the deleted vertex collection is still shown in the list of vertex collections, as displayed in the output below.

```
pcb_deletion_bravo_SurModGe_jvzho5ye_1558545378186_exp_data # collection name
['pcb_deletion_bravo_BNL_data_jvzhkx93_data', 'pcb_deletion_bravo_SurModGe_jvzhlvaq_1558545261656_exp_data', 'pcb_deletion_bravo_SurModGe_jvzhlvaq_1558545262193_exp_data', 'pcb_deletion_bravo_SurModGe_jvzho5ye_1558545369145_exp_data', 'pcb_deletion_bravo_SurModGe_jvzho5ye_1558545378186_exp_data', 'pcb_deletion_bravo_SurModGe_jvzho5ye_1558545378341_exp_data', 'pcb_deletion_bravo_SurModGe_jvzho5ye_1558545378515_exp_data', 'pcb_deletion_bravo_SurModGe_jvzho5ye_1558545378663_exp_data', 'pcb_deletion_bravo_SurModGe_jvzho5ye_1558545378803_exp_data', 'pcb_deletion_bravo_SurModGe_jvzho5ye_1558545378965_exp_data', 'pcb_deletion_bravo_SurModGe_jvzho5ye_1558545380791_exp_data']
```

However, deleting edge definitions works like a charm. Manually deleting the vertex collection using ArangoDB's web interface works as well. I am using ArangoDB version 3.3.3.

Thank you for your help!

**Comment by joowani** [comment]
Hi @agentS,

My first guess would be that the vertex collection is not an "orphan" and is tied to a graph, which is why the deletion fails. Is the request raising any exceptions? Also would it be a possibility to try the same thing on ArangoDB version 3.4?

**Comment by agentS** [comment]
After upgrading ArangoDB to version 3.3.23 the code works now. Thank you so much!
