### ISSUE TITLE
Cannot connect to ArangoDB server with non-standard URL

### ISSUE THREAD

**Issue by borja010** [joowani/python-arango#102]
Good day,

I would like to ask your assistance with the following error that Im encountering:
raise ServerStatusError(resp, request)

ServerStatusError: [HTTP 404] Not Found

Im trying to connect to http://host:port/arango, but if I dont setup a port, the connection automatically change it to http://host:port/arango:8529.

How can I address this?

Thank you in advance for your support.

**Comment by joowani** [comment]
Hi @borja010,

Unfortunately I've never considered this case. This is a design flaw/limitation in python-arango and I will have to address this in future releases.

For now, you must create a custom client which overrides the initialization method like this:
```python
from arango import ArangoClient


class CustomClient(ArangoClient):

	def __init__(self, url, http_client=None):

		super(CustomClient, self).__init__(
			protocol='http',
			host='host',
			port=8529,
			http_client=http_client
		)
		self._url = url

client = CustomClient('http://host:port/arango')
```

Let me know if that works for you.

**Comment by borja010** [comment]
Good morning,

Thank you very much for the information. I did the changes and its working right now.
