### ISSUE TITLE
Custom JSON Serializer

### ISSUE THREAD

**Issue by apurvNfer** [joowani/python-arango#103]
Please provide an option to pass a custom json serializer while inserting documents.

**Comment by joowani** [comment]
Hi @apurvNfer,

Right. I will consider adding it in the next release. Keeping this open for any updates.

**Comment by joowani** [comment]
Hi @apurvNfer,

Python-arango version 5.0.0 is now up! This release provides support for [custom JSON serialization](https://python-driver-for-arangodb.readthedocs.io/en/master/serializer.html). 

But please note that this version only works with ArangoDB 3.5+ and breaks backwards-compatibility (you will need to update your application code when you upgrade). Please see the [release notes](https://github.com/joowani/python-arango/releases/tag/5.0.0) for details.

Thanks!
