### ISSUE TITLE
how python-arango  call ArangoSearch?

### ISSUE THREAD

**Issue by Himan000** [joowani/python-arango#104]
how python-arango  call ArangoSearch?

**Comment by joowani** [comment]
Hi @Himan000,

ArangoSearch support will be added in the next release. It's coming soon!

**Comment by Himan000** [comment]
OK，great, looking forward to it.

**Comment by joowani** [comment]
HI @Himan000,

I forgot to mention that the new release 5.0.0. will only be compatible with ArangoDB 3.5, which is not yet released (I am trying to release the driver around the same time). I apologize for any inconvenience but I just don't have the time to work on backward compatibility.

**Comment by Himan000** [comment]
Hi @joowani ,
It's OK. Thank you for your update info.
