### ISSUE TITLE
Add error code constants

### ISSUE THREAD

**Issue by mooncake4132** [joowani/python-arango#107]
Is it possible to add the [error code constants](https://www.arangodb.com/docs/stable/appendix-error-codes.html) into the arango package? I'm thinking of adding a `errno.py` with each a mapping for each error code:
```py
ERROR_NO_ERROR = 0
ERROR_FAILED = 1
...
```
This way, to check for a particular kind of error (i.e. conflict error), instead of writing:
```py
if result.error_code == 1210:
   generate_new_key()
```
I can write:
```py
if result.error_code == arango.errno.ERROR_ARANGO_UNIQUE_CONSTRAINT_VIOLATED:
   generate_new_keu()
```

I can create a PR for this if you like the idea.

**Comment by joowani** [comment]
Hi @mooncake4132,

That would be nice addition! If you submit a PR I would be happy to take a look. 
I am tempted to remove the "ERROR_ARANGO" part from "ERROR_ARANGO_UNIQUE_CONSTRAINT_VIOLATED" just to keep things shorter.
