### ISSUE TITLE
Unintentional loading of all collections

### ISSUE THREAD

**Issue by hkernbach** [joowani/python-arango#11]
When using command: db.collections['collection_name']
the driver is collecting all properties of every collection. At the moment this is only possible if a collection is loaded. So the side effect is that every unloaded collection will get loaded. If someone has a very large database, this could take a while. I guess this behaviour is not wanted.

**Comment by joowani** [comment]
Hi hkernbach,

Thanks for pointing this out. I will be working on the next release where everything will be lazily loaded. I will make sure to handle this case as well.

**Comment by joowani** [comment]
Hi hkernbach,

python-arango version 3 is finally out now. In this version everything is lazy loaded. Give it a try when you have time and let me know if you have any other problems!

Thanks
