### ISSUE TITLE
Change data capture support

### ISSUE THREAD

**Issue by michielhub** [joowani/python-arango#110]
Hello

I was wondering if there are any plans for adding change data capture support? I'm looking for something that listens to changes made to a graph collection so that I can consume these events and do something with them.

I came across this project but it is dead: https://github.com/baslr/arangochair.

**Comment by joowani** [comment]
Hi @michielhub,

Unfortunately the short answer would be no. Exposing the replication API (which arangochair seems to use under the hood)  is in the roadmap but building the actual poller is out of the scope of this client.

**Comment by joowani** [comment]
But it shouldn't be too hard to build yourself. All it seems to do is query the two endpoints (which you will be able to do using python-arango in its next release) in a while loop.

**Comment by joowani** [comment]
Hi @michielhub, 

Replication API is now available in the latest version of python-arango. Building a checker on top of these should not too much work.
