### ISSUE TITLE
custom http client docs out of date

### ISSUE THREAD

**Issue by ex-nerd** [joowani/python-arango#112]
It looks like `arango.http.HTTPClient` no longer has a `_session` property, which results in problems trying to implement the example code in 'https://github.com/joowani/python-arango/blob/master/docs/http.rst`

Specifically, the `self._session.mount('https://', adapter)` line generates an an error saying `'CustomHTTPClient' object has no attribute '_session`.

**Comment by joowani** [comment]
Hi @ex-nerd,

Right, it has to be just `session` instead of `self._session`. I will correct that soon.
Thank you for reporting it.

**Comment by joowani** [comment]
The doc should be fixed now.
