### ISSUE TITLE
DocumentUpdateError / Method not supported on wrong data

### ISSUE THREAD

**Issue by Sushi2all** [joowani/python-arango#116]
I was having an issue with updating a document in arango when I got the following error:

`arango.exceptions.DocumentUpdateError: [HTTP 500][ERR 405] method not supported`

I tried several things and in the end the problem was actually the data I was sending in the `vertex_collection.update` method, not the method itself (the document key was missing).

I'm raising the issue just to say that the error raised is a bit misleading and maybe should be fixed.

Other than that, great library, really easy and intuitive to work with. Hat off! 👏 🎩

**Comment by joowani** [comment]
Hi @Sushi2all,

Thanks for the kind words! I'm glad you find the library useful.

The message is actually coming directly from ArangoDB. Python-arango simply passes along all server error details and tries not to touch them as much as possible. So this actually looks like a bug on ArangoDB's part. The error code and message seem incorrect.
