### ISSUE TITLE
Version 5.2.1 on PyPI, not on GitHub

### ISSUE THREAD

**Issue by themowski** [joowani/python-arango#118]
Currently, PyPI shows 5.2.1 as the latest version of python-arango, but the releases page here on GitHub only has 5.2.0.

PyPI: https://pypi.org/project/python-arango/#history

GitHub: https://github.com/joowani/python-arango/releases

Is current master actually version 5.2.1, just untagged & unreleased here on GitHub?

**Comment by joowani** [comment]
Hi @themowski,

Thanks for pointing this out. I forgot to make a new release. It is now created.
And yes as of this writing the master is version 5.2.1 (you can check by looking at version.py).
