### ISSUE TITLE
[4.4] No exception when using the wrong protocol

### ISSUE THREAD

**Issue by aringot** [joowani/python-arango#119]
Hi joowani,

I use python-arango 4.4, and when I create an ArangoClient with the parameter protocol='https' (instead of 'http') my script starts hanging as soon as I try to connect to the database (I have set the verify parameter to true, if set to false I get the problem at the first request). The lack of exception makes it really hard to debug.

It would be great if unsupported/invalid configurations could trigger an exception.

Thanks in advance.
Alexis

**Comment by joowani** [comment]
Hi @aringot,

I've added a default timeout of 5 seconds in python-arango version 7.0.0. It should not hang indefinitely anymore.
