### ISSUE TITLE
Question: Would be ORM set in project milestones?

### ISSUE THREAD

**Issue by rafaelpivato** [joowani/python-arango#12]
This projects is very interesting and has apparently the best arrange of documentation, frequent updates and code style among other ArangoDB Python drivers.

In order to use this project it would be good having a sense whether is part of the scope adding some ORM classes to it, or if that should be part of another project, having this as a base for a lower level access to ArangoDB.

**Comment by joowani** [comment]
Hi rafaelpivato,

Thank you for your interest in python-arango.
My priority is to making sure that I cover all of ArangoDB's API endpoints and that the API of python-arango itself is as minimal, efficient and clean as possible. ORM is definitely on my radar, however, and is certainly in my realm of exploration.

**Comment by kashifpk** [comment]
Hi,

@joowani @rafaelpivato - Perhaps joowani can focus on making the API complete in python and another person or group could start building an ORM layer on top of it. I agree that the usage of this package closely resembles arangosh so it has minimal learning curve. The ORM on top of it could make things a lot simpler and quicker for developers.

**Comment by brianrusso** [comment]
My personal opinion is I'd like this to remain the clean, uncluttered low
level API it is. There is pyArango if someone wants an ORM.

$0.02

**Comment by kashifpk** [comment]
Perhaps then we could launch a separate package for ORM that depends on this one, keeps this one clean and for those of us who'd like the ORM, they can just install an additional package.

**Comment by joowani** [comment]
Yea for now the scope of this project will remain at the API level without the ORM. 
Thanks for your interest in python-arango (version 3 is finally out now btw).

**Comment by sebastiancodes** [comment]
@kashifpk FYI: I've started on something that depends on both
python-arango and marshmallow (see https://github.com/sebastiancodes/marshmallow_arango) but I wouldn't call this the best thinkable ORM implementation.

**Comment by kashifpk** [comment]
@sebastiancodes this looks good. In the example, why do we need a model and a schema? In any case it's really something to begin with :-)

**Comment by kashifpk** [comment]
@sebastiancodes @joowani @rafaelpivato - I've started working on an orm layer for arango using python-arango. Please take a look here: 

    https://github.com/threatify/arango-orm

Your suggestions and opinions are welcome.

**Comment by iamale** [comment]
@kashifpk @sebastiancodes Nice integrations you've written guys! How do your implementations handle `load_only` / `dump_only` (i. e. if we want the user to be able to set some value through the API, but not get it) though?

**Comment by iamale** [comment]
Or in this case two schemas should be used?

**Comment by kashifpk** [comment]
@imale - my plan was that arango-orm would be used within an API implementation layer so access rights (ready-only or write-only) would be handled by the API.
