### ISSUE TITLE
foxx client does not support binary upload formats to foxx REST API

### ISSUE THREAD

**Issue by ex-nerd** [joowani/python-arango#120]
The foxx REST API supports uploading service binaries (`.js`, `.zip`, etc) instead of specifying server-side or URI file locations: https://www.arangodb.com/docs/stable/http/foxx-management.html#install-new-service

Please support this feature, since it makes managing foxx services a LOT easier (and would bring this library closer to parity with the official foxx-cli client).  Support for straight binary and `multipart/form-data` bodies is [fully supported in `requests`](https://2.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file), so it should just be a matter of tweaking the foxx client create/upgrade/replace method signatures (and associated http client "send request" functions) to allow for a `files` property to be passed along with `source` (the value of which would then be used to refer to the attached file name).  If you add a `files` section to a `requests` request, the `data` property will automatically be converted from POST data to multi-part form fields.

E.g.

```python
service = foxx.create_service(
    mount="/my_mount",
    source="source-attachment"
    config={},
    dependencies={},
    files={
        "source-attachment": ('my-mount-service.zip', open('/path/to/my-mount-service.zip', 'rb'), 'application/zip', {'Expires': '0'})
    },
    setup=True,
    legacy=False,
)
```

**Comment by ex-nerd** [comment]
It looks like this is slightly more complex than I originally thought, but actually makes some of the method signature changes easier.  However, in it does add a dependency on `requests_toolbelt` to get around the lack of proper buffer support in `requests` itself.

It shouldn't be too hard to detect that `params.source` is defined as a `tuple` instead of a string, and if so, initialize it as a `MultipartEncoder` instead of a `dict`.  The following sample code shows the proper sequence

```python
import requests
from requests_toolbelt.multipart.encoder import MultipartEncoder

data = MultipartEncoder(fields={
    "source": ("file.zip", open("/path/to/file.zip", "rb"), "application/zip"),
    "configuration": {},
    "dependencies": {},
}

params = {
    "mount": "/my-service-mount",
    "development": False,
    "setup": False,
    "legacy": False,
}

session = requests.Session()
req = requests.post(
    url=url_prefix + "/_api/foxx",
    headers={"Content-Type": data.content_type},
    params=params,
    data=data,
    # ... auth=auth, etc.
)

```

**Comment by joowani** [comment]
Hi @ex-nerd,

Ok I will take a look and see if I can include this in the next release. Thanks

**Comment by joowani** [comment]
Hi @ex-nerd,

New [release](https://github.com/joowani/python-arango/releases/tag/5.3.0) is now out with binary upload support for foxx.
Please check it out and let me know if you have any problems or questions.

**Comment by ex-nerd** [comment]
@joowani Seems like it's still missing variants for replace/update.

**Comment by joowani** [comment]
Hi @ex-nerd,

**Comment by joowani** [comment]
@ex-nerd I'm not sure why but ArangoDB seems to return 405 (method not allowed) on update and replace. I've referenced the ticket to this one above. I plan to add the methods once it is fixed. Perhaps you could test it out and confirm my results.

**Comment by joowani** [comment]
Oh perhaps I simply got the endpoint wrong. I'll check again and get back to you.

**Comment by joowani** [comment]
Added the two missing methods for update and replace in release [5.4.0](https://github.com/joowani/python-arango/releases/tag/5.4.0)

**Comment by pluma** [comment]
https://github.com/joowani/python-arango/issues/120#issuecomment-579553800

FYI it looks to me like the configuration and dependencies fields here are specified as Dicts rather than strings. If present they must be passed as regular form fields containing JSON strings. I'm not sure what passing a Dict instead does here but I could imagine this resulting in unexpected behavior.

**Comment by joowani** [comment]
Hi @pluma,

Are you saying it should look more like this:
```
data = {
    "source": (filename, open(source_path, "rb",), "application/zip",),
    "configuration": '{"key": "value"}',
    "dependencies": '{"key": "value"}',
}
```
It would be nice if ArangoDB [documentation](https://www.arangodb.com/docs/stable/http/foxx-management.html) had more concrete examples.

**Comment by pluma** [comment]
@joowani The docs state that all three values are "fields" (i.e. regular text fields) and then says that "source" can alternatively be a "file field". In the context of multipart these are the only two types that can be represented.

See my comment on the ArangoDB issue https://github.com/arangodb/arangodb/issues/11045#issuecomment-701381388 for an example of how the payload should look. As `multipart/form-data` was originally created for HTML forms, it helps to imagine how this would look in a form:

```html
<textarea name="configuration">json goes here</textarea>
<textarea name="depenencies">json goes here</textarea>
<input type="file" name="source">
```

I've looked into the implementation of `MultipartEncoder` and it seems to delegate the actual field handling to [urllib3](https://github.com/urllib3/urllib3/blob/master/src/urllib3/fields.pyi) but it looks like it allows for two input types:

1. A plain string (confusingly named `file_pointer` but `urllib3` makes it clear this is actually a string instead).
2. A tuple of a string (internally called `file_name`) and 1-3 additional values (internally named `file_pointer`, `file_type` and `file_headers`).

In the former case a simple text field is added to the form. In the latter a file field will be added. I didn't dig deep enough to find out what passing a `Dict` will do but it's clearly not defined (nor documented) behavior. So there really would only be two ways to represent the JSON config in a multipart form: as a regular field (i.e. converted to a string) or as a file field (i.e. as a binary blob or file pointer with a file name, file type and optionally additional headers).

**Comment by joowani** [comment]
Hi @pluma,

Ok thanks for the info. I'll change it from dict to json string.

**Comment by joowani** [comment]
Made the changes in the release 6.1.0.
