### ISSUE TITLE
Document creation works from shell but not from web user

### ISSUE THREAD

**Issue by gitman23** [joowani/python-arango#121]
Because I cannot execute python scripts from web interface I have a php script which executes the python. The end user enters a value x in a form and I want to write it in my arangodb collection 'coll'

When executing the python script.py with variable x in the shell it writes the variable x into a new document in the collection.
When executing the python script.py from program.php, then scipt.py is executed as well but one line isn't working:
coll.insert({'_key: x})

I assume it has to do with permissions. That the sudo owner of script.py can write with the script in the collection but the apache user www-data not.
By the way the php script has the same owner as the python script.

I tried now for hours but don't get it fixed. I tried to change owners of the scripts or chmod s+u for the python etc..

Any good idea how to fix this issue? Trying to avoid using one of the arango php libraries (because I need it only for this one line of code)

Thanks in advance!

**Comment by joowani** [comment]
Hi @gitman23,

Is there no way for you to see the error stacktrace of script.py?
Also, in the line you are missing a quote. I should be: `coll.insert({'_key': x})` not `coll.insert({'_key: x})`

**Comment by gitman23** [comment]
Hi, thank you!
if I stack trace on the shell with
python3 -m pdb script.py 
I don't get an error which I expected because in the shell the script works well.

Any hint how to stack trace if the script is started from a php script via web interface?

Tks.

**Comment by joowani** [comment]
```
Any hint how to stack trace if the script is started from a php script via web interface?
```
Hmm perhaps you could catch all exceptions within the python script and have it write to a log?
I'm not familiar with php. There is also a PHP driver for arangodb you could try: https://github.com/arangodb/arangodb-php

**Comment by gitman23** [comment]
I followed your advise and got this Error:
<b>[HTTP 404][ERR 404] not found</b>
when the script is in this line:
<b>coll.insert({'_key': x})</b>

https://www.arangodb.com/docs/stable/http/collection-modifying.html
says this means "404: If the collection-name is unknown, then a HTTP 404 is returned."

Any idea what this means in this context? I know that the collection exists... .
Thank you!

**Comment by joowani** [comment]
Hi @gitman23,

Without looking at logs or stacktraces it's hard for me to help you. I suggest you look at ArangoDB's logs if you have access to it.

**Comment by gitman23** [comment]
I found a work around. It has nothing to do with permissions but 
coll.insert({'_key: x})
If and only if the string x contains a slash "/" as character the insertion isn't working.
I had in each insert a slash so I didn't realize this before. 
I replace now all slash by Underscore "_" which works well and is fine for my use case.

Generally are there characters not allowed to insert if using python-arango?
Thanks!

**Comment by joowani** [comment]
Glad that you found the issue!

According to the [documentation](https://www.arangodb.com/docs/stable/data-modeling-naming-conventions-document-keys.html) from ArangoDB, the `/` character is not allowed in document keys (not to confuse with document ids/handles which DO allow one `/` character). 

Python-arango simply passes along the data provided by you to ArangoDB via its HTTP REST API. So no the driver itself does not impose any extra restrictions on top.
