### ISSUE TITLE
Cursor with no count throws TypeError for len() and if

### ISSUE THREAD

**Issue by ex-nerd** [joowani/python-arango#123]
When executing an AQL query with `count=False`, the resulting Cursor fails to work as expected in a pythonic way:

```
# docs
<Cursor>
# docs is None
False
# len(docs)
TypeError: 'NoneType' object cannot be interpreted as an integer
# if docs: True
TypeError: 'NoneType' object cannot be interpreted as an integer
# docs.count()
None
```

In order to get this to behave properly, the Cursor must be drained into a list.  I realize this depends a bit on whether the `count` of `True` vs `False`, but it would be a lot more helpful if these functions raised some sort of `arango.exception` telling the user to enable the count option instead of simply bumping into the unhelpful `TypeError`.

**Comment by joowani** [comment]
Hi @ex-nerd,

Thanks for pointing this out.
I've changed it so that `CursorCountError` (inherits TypeError) is raised with a more helpful message in the latest release 5.4.0. Let me know if you see any other problems.
