### ISSUE TITLE
Help needed: How to create index and perform search using it?

### ISSUE THREAD

**Issue by poul1x** [joowani/python-arango#124]
I know, that search by `_key`, or `_id` is possible. But can I create another index, perhaps, on `username` field, and get document by that key?

**Comment by joowani** [comment]
Hi @poul1x,

Yes you can! Please see [here](https://python-driver-for-arangodb.readthedocs.io/en/master/indexes.html) to find out how to create indexes (hash index probably for username). You can then use [Collection.find](https://python-driver-for-arangodb.readthedocs.io/en/master/specs.html#arango.collection.StandardCollection.find).

**Comment by poul1x** [comment]
Ok, thanks
