### ISSUE TITLE
Connecting to Oasis

### ISSUE THREAD

**Issue by milko** [joowani/python-arango#125]
Is it possible to connect to Oasis with this library? It would be nice if there could be one example in the documentation, if that is possible. (On Oasis they have an example that uses PyArango).

**Comment by joowani** [comment]
Hi @milko,

Could you please give me the link to the example? Thanks.

**Comment by milko** [comment]
I cannot send you the link, because it is a page in my account, but I am sending you the connection example they provide.
The thing is that I find python-arango driver has much better documentation and features than PyArango, so I would like to use it. The problem is that there is nowhere mentioned how to use certificates, which are required to connect to the Oasis ArangoDB cluster.

I am sending you the print-screen of the example they provide.

Thanks

Milko

**Comment by milko** [comment]
For some reason the screen shot didn't get it here. The example they had was for PyArango, here it is:

`import pyArango.connection as ADB`

`encodedCA = "<the encoded certificate>"`
`cert = ADB.CA_Certificate(encodedCA, encoded=True)`
`connection = ADB.Connection(`
`	arangoURL = '<the database URL>',`
`	username = "root",`
`	password = "<get-from-dashboard>",`
`	verify = cert`
`)`

`print( "ArangoDB:", connection.getVersion() )`

Hope it helps, would be very nice to use python-arango driver.

**Comment by joowani** [comment]
Hi @milko,

I'll take a look and see if I can add this in the next release (probably in a couple of weeks). Thanks.

**Comment by milko** [comment]
Thanks a lot, this will be very useful!
