### ISSUE TITLE
AL2 open-source license

### ISSUE THREAD

**Issue by bzurkowski** [joowani/python-arango#126]
Any chance of distributing python-arango under Apache License 2.0, the same as ArangoDB itself? It would make use of the library more straightforward in other open-source projects.

For example, in [CNCF](https://github.com/cncf/foundation/blob/master/whitelist-policy.md), the MIT license is whitelisted, but additional requirements are imposed to be satisfied, whereas with AL2 license there is no question.

**Comment by joowani** [comment]
Hi @bzurkowski,

From what I understand MIT license is supposed to be more permissive than Apache License 2.0.
I'm not sure what #2 in CNCF's whitelist policy means: "It is stored unmodified in a designated third-party folder". I believe python-arango meets the other two.

**Comment by bzurkowski** [comment]
That's right. MIT is a little bit more permissive than AL2. Anyway, CNCF treats it differently. For sure, it's not a problem for python-arango since it is a mature project with a substantial number of applications.

To be honest, I don't quite understand the "designated third-party folder" neither. I guess, installing the package using pip and not monkey patching the package's codebase should be enough? Must confirm.

I am new on the CNCF road. That's why my licensing request is probably unnecessary and inappropriate. Thanks for the response! Closing.
