### ISSUE TITLE
Load edges with preloaded vertex data

### ISSUE THREAD

**Issue by bzurkowski** [joowani/python-arango#127]
First off, thanks for creating the library. Really like its simple and intuitive interface! 🎉👍

I am struggling to filter out graph edges with vertex data preloaded in the response. So far I was trying to load edges using `find` method in edge collection's API wrapper, like this:

```python
edges = graph.edge_collection('mylinks').find(query)
```

However, the `find` method returns a dict with `_from` and `_to` keys that contain only references to connected vertices (document handles). I have to perform two additional requests to the database in order to fetch vertex data for source and target vertices.

Is there an easy way in python-arango to accomplish this? Or, should I fallback to AQL? If so, do you have any examples for constructing the required query?

**Comment by joowani** [comment]
Hi @bzurkowski,

Thanks for using python-arango! Glad it helps.
I think what you are looking for is graph [traversals](https://python-driver-for-arangodb.readthedocs.io/en/master/graph.html#graph-traversals)? If that does not meet your requirements you will probably need to use AQL (python-arango does not provide an ORM interface).

**Comment by bzurkowski** [comment]
Thanks for the answer @joowani. I managed to retrieve both edge data and vertex data in one bulk by using a custom AQL query:
```python
query = (
    'LET link = DOCUMENT("links/mylink") '
    'LET source = DOCUMENT(link._from) '
    'LET target = DOCUMENT(link._to) '
    'RETURN {link: link, source: source, target: target}')
cursor = db.aql.execute(query)
documents = list(cursor)
```
Not sure about the performance of such query though.

The suggested graph traversal API works as well, but it requires a weird JS-syntax function for filtering out the concrete edge instance.
