### ISSUE TITLE
Is the insert_dict() function run asynchronously?

### ISSUE THREAD

**Issue by valentingregoire** [joowani/python-arango#128]
When doing some unit tests in Python, I insert 10 test documents into a test ArangoDB. I do this by creating a generic dictionary with some fields. Then with a for loop, I create 10 instances of this generic dictionary and modify it slightly to have 10 different test documents which I insert 1 by 1 in this for loop. However, after this piece of code, I perform a `search` and receive only a couple of my 10 documents because they were not all inserted yet. If I put a 1 second `sleep` after my 10 insertions, I do receive my 10 test documents. It seems that these inserts are run asynchronously.

This is my example code: 

```python
    def load_test_data(self) -> None:
        # this is run from the setUp() method
        # inserts 10 test users and test projects
        logging.info("Loading test data...")
        for i in range(1, 11):
            project = test_utils.get_default_test_project()
            project['id'] = i
            project['name'] += str(i)
            project['description'] = f"Description for project with the id {i}"
            # tried line below with several of the possible parameters, even with sync and return_new it is the same result
            db.insert_document(collection_name, dictionary, sync=True, return_new=True)
            # sleeps 1 second because for some reason, during the tests, it seems that not all inserted are found yet.
            # TODO: Find a way to not use this with a sleep.
        # sleep(1)
```
My test would be something simple like this:
```python
     def test_search_by_project_path_with_namespace(self) -> None:
        actual = dao.search("test")
        self.assertEqual(10, len(items))
```
Resulting in this (without the `sleep(1)`):
```
Ran 1 test in 1.693s

FAILED (failures=1)


6 != 10
```

**Comment by joowani** [comment]
Hi @valentingregoire,

What version of ArangoDB are you using? Also, when you created the collection, did you set the ``sync`` parameter to True?

**Comment by valentingregoire** [comment]
@joowani I am using version 3.6.0 of ArangoDB (Community edition). As for the `sync` parameter, you can see in my example code that I indeed use the parameter. I have tried it with and without the parameter, it makes no difference.

**Comment by valentingregoire** [comment]
Hello @joowani 

I use ArangoDB version 3.6.0 (Community edition). As for the `sync` parameter for the collections, I had not turned this flag on. I edited my collections and set this flag to `true`, but the result is the same.
Does it matter if I create the collections with the `sync` flag set to `false` and later on change it to `true`, or if I would create the straight with the `sync` parameter set to `true`?

**Comment by joowani** [comment]
HI @valentingregoire,

Could you show me what your `dao.search` is doing exactly? Thanks.

**Comment by valentingregoire** [comment]
Hi @joowani 

I reached out to the people of ArangoDB and it appears that Views don't update right away when documents get inserted into a collection. They gave me a `search option` that I could enable, but it's an internal option which they use for testing themselves and it is highly discouraged to use this option.
