### ISSUE TITLE
bulk import from python dataframe

### ISSUE THREAD

**Issue by ovidius1980** [joowani/python-arango#129]
Hello joowani
I am trying to import a huge amount of data from xlsx files to arangodb. The files are very big (10 to 25 MB) and have at least 25 worksheets. I wrote a code that reads every file and creates a dataframe for every worksheet. Then it writes the dataframe to a .json file, it opens it, reads it, loading the json data and bulk imports it to the appropriate colloction. The issue is  is that writing the json file takes a lot of time, hard disk space and some times crashes the program because some of these json files are massive. So Itried something like this :

`df = pd.read_excel("file.xlsx", sheet_name = "worksheet", header = 1)`
`df1 = df.to_json(orient='records')`
`collection = db.collection("collection_name")`
`collection.import_bulk(df1)`
But when I run it I get this error:

>  DocumentInsertError: [HTTP 400][ERR 1227] invalid document 
>
Could you please explain why is this happening and maybe help me achieve the bulk import of the data?

**Comment by joowani** [comment]
Hi @ovidius1980,

From the error code, it seems some of the documents are of invalid type. You could check the ArangoDB logs for more details (see ArangoDB docs). You could also trying batching the process a bit more so you can easily narrow down the problematic ones.

**Comment by joowani** [comment]
Hi @ovidius1980,

Closing this ticket due to inactivity. Please feel free to re-open if you have any further questions.

**Comment by bjornjorgensen** [comment]
Hi, using pandas dataframe you must have the line=True and you most save it to a file.
With code works :) 


import json

def gen(file_name):
    with open(file_name) as fh:
        while line := fh.readline():
            yield json.loads(line)

df1 = df.to_json("form3_test.json", orient='records', lines=True)

data = gen("form3_test.json") 
           
collection = db.collection("test")
collection.import_bulk(data)
