### ISSUE TITLE
AQL query: count of document returned

### ISSUE THREAD

**Issue by migueltubia** [joowani/python-arango#13]
Hi,

when I execute a query as:
```
cursor = my_db.execute_query(
  "FOR d IN my_col FILTER d.value == 'value' RETURN d"
)
```
How can I know if the resultset has values or is empty?
If I try to do:
```
for doc in cursor:
  print doc
```
I get this error:
`'generator' object has no attribute 'current'`

Thanks for your help.
M.

**Comment by migueltubia** [comment]
Ah, I'm ussing python 3.4, ArangoDB 2.8.9 and arango driver for python version 2.2.0
```
pip3 show python-arango
---
Metadata-Version: 1.1
Name: python-arango
Version: 2.2.0
Summary: Python Driver for ArangoDB
Home-page: https://github.com/joowani/python-arango
Author: Joohwan Oh
Author-email: joohwan.oh@outlook.com
License: UNKNOWN
Location: /usr/local/lib/python3.4/dist-packages/python_arango-2.2.0-py3.4.egg
Requires: requests, nose
```
Thanks!!

**Comment by migueltubia** [comment]
Hi again,

ok, my fault. After some research and fix some bugs in my code I can do a loop:
```
for doc in cursor:
  print (doc)
```
Anyway, is there any way to get the resulset count? I have read that I cann the 'count' parameter to execute_query. How can I get the value?

Thx!!

**Comment by joowani** [comment]
Hi migueltubia,

Unfortunately there is no way you can get the count from cursors yet. 
It will be one of the first things I will add in the next release.

Sorry for the inconvience
Joohwan

**Comment by migueltubia** [comment]
Hi @joowani !

thanks for your response!! I'll wait then next release.

Best regards and thanks for your work!!
M.
