### ISSUE TITLE
bind variable

### ISSUE THREAD

**Issue by yiya-core** [joowani/python-arango#130]
hi, i try to insert data from a variable and can't find a way to do this, can someone help me? something like this:

name = "mark"
surname = "clark"

db.collection('user').insert([{'username': @name, 'usersurname': @surname}])

thanks!

**Comment by joowani** [comment]
Hi @yiya-core,

You should not need to use bind variables with `Collection.insert`. You could just do the following?
```python
document['name'] = 'mark'
document['surname'] = 'clark'

db.collection('user').insert(document)
```

If you are talking about bind variables for raw AQL queries, then there is an example in this [page](https://python-driver-for-arangodb.readthedocs.io/en/master/aql.html).

**Comment by yiya-core** [comment]
sorry, i'd like to do as you reccomand...  i'm very new in coding, can't find a way...thanks for your patience!

**Comment by joowani** [comment]
Hi @yiya-core,

No problem. I hope it helped and I wish you good luck with your project.
