### ISSUE TITLE
Incorrect error string returned for missing vertex collections

### ISSUE THREAD

**Issue by ex-nerd** [joowani/python-arango#131]
Given a graph `G` that links `V_DOCS` to itself via edge collection `EDGE_DOCS`, I accidentally typo'd my link statement in something that looks roughly like this:

```python
g: Graph = db.graph("G")
edges: EdgeCollection = g.edge_collection("EDGE_DOCS")
edges.insert({"_key": "something", "_from": "V_TYPO/1234", "_to": "V_DOCS/3456"})
```

The error returned looks like this:

`arango.exceptions.DocumentInsertError: [HTTP 404][ERR 1203] collection 'EDGE_DOCS' not found`

Certainly `EDGE_DOCS` exists ... what the error *should* have been telling me is that the vertex referencing `V_TYPO` doesn't exist.  I don't know if this information is available in the 404 from arangodb but it would have been more helpful to get a vague error message than spend a bunch of time trying to figure out why I could query my `EDGE_DOCS` edges in the arangodb UI but this was failing in my python code.

**Comment by joowani** [comment]
Hi @ex-nerd,

The error message is coming from ArangoDB. Python-arango tries not to touch them (as doing so will be too much to maintain). You should report this bug to ArangoDB team. Thanks!

**Comment by ex-nerd** [comment]
Done, thanks. https://github.com/arangodb/arangodb/issues/11730
