### ISSUE TITLE
Adding a utility function to convert to _key

### ISSUE THREAD

**Issue by wshayes** [joowani/python-arango#134]
I have a utility function for converting a string to a valid _key for arangodb - is this something that you'd be interested in a PR for to go into the arango/utility module?  If so, there isn't currently a Misc or Utility section in the docs - do you have a preference on where to insert documentation for it?

**Comment by joowani** [comment]
Hi @wshayes,

Could you please go into more details about this function (preferably with an example)?
Normally I would place the code in arango.utils module, and the documentation in a new page called "Utilities".

**Comment by wshayes** [comment]
@joowani something like this:

```
def str_to_key(key):
    """Remove illegal chars from potential arangodb _key

    Args:
        key (str): string to be used as arangodb _key

    Returns:
        (str): _key value with illegal chars removed
    """

    key = re.sub(r"[^a-zA-Z0-9\_\-\:\.\@\(\)\+\,\=\;\$\!\*\%]+", r"_", _id)

    if len(key) > 254:
        log.error(f"Arango _key cannot be longer than 254 chars: Len={len(key)}  Key: {key}")
    elif len(key) < 1:
        log.error(f"Arango _key cannot be an empty string: Len={len(key)}  Key: {key}")

    return key
```

I use this in many of my projects - figured it might be good to have in your library.

**Comment by joowani** [comment]
Hi @wshayes,

This seems like a very client specific way of handling document keys. Some users may not want their incorrectly formatted keys to be fixed and inserted into the database sliently. Python-arango aims to be agnostic and avoid custom logic.
