### ISSUE TITLE
Describe desired database state

### ISSUE THREAD

**Issue by wshayes** [joowani/python-arango#135]
No idea if this is of interest for this library. I reuse a fair amount of code to create idempotent updates of databases/collections/indexes. Pretty much every time I start one of my services, it checks to see if the database exists, then the collections, and then checks the indexes to make sure they are what I've specified in the code. 

In updating my code, I've realized I basically want to describe my desired state and then have my code idempotently implement that state. Is there any interest in doing that here? If not, I'll create a new library for that based on your wonderful library.

**Comment by joowani** [comment]
Hi @wshayes,

Due to resource and time constraint, python-arango will remain to be a thin layer on top of ArangoDB's REST API and no more (at least for the foreseeable future). Any features outside of that should be placed in separate libraries. Thanks
