### ISSUE TITLE
ArangoDB 3.7 removes MMFiles support

### ISSUE THREAD

**Issue by 153957** [joowani/python-arango#138]
ArangoDB 3.7 removes support for MMFiles [1], I still see some references to that storage engine in the code in the dev branch.

Any options specifically related to that storage engine can be removed.

Do you want help, i.e. a PR, with this task?

[1] https://www.arangodb.com/2020/03/upcoming-arangodb-3-7-storage-engines/

**Comment by joowani** [comment]
Hello @153957,

Thanks for pointing this out, and sure! Any help is greatly appreciated.

**Comment by 153957** [comment]
Ok I will work on this!

For reference: https://www.arangodb.com/docs/3.6/appendix-deprecated.html
> The collection attributes `doCompact`, `indexBuckets`, `isVolatile`, `journalSize` and `path` are only used with MMFiles and are thus also deprecated.

**Comment by 153957** [comment]
Done in #140
