### ISSUE TITLE
Schema validation in ArangoDB 3.7

### ISSUE THREAD

**Issue by 153957** [joowani/python-arango#139]
ArangoDB 3.7 adds support for schemas for collections [1], which allows ArangoDB to validate documents when they are inserted/updated in collections. Support for this can be added to `Database.create_collection`. Im not certain if other places also need changes, maybe new exceptions for validation errors?

Is this something you are likely to add? And are there any specific parts of this you would like contributions for?

[1] https://www.arangodb.com/arangodb-training-center/schema-validation-tutorial/

**Comment by joowani** [comment]
Hi @153957,

Thanks for pointing this out. Yes I will add this feature. Looks like I missed a big one.

**Comment by joowani** [comment]
Support for schema has been added in dev branch and will be released with ArangoDB 3.7!
