### ISSUE TITLE
EdgeCollection and VertexCollection should inherit some methods from StandardCollection

### ISSUE THREAD

**Issue by nickb937** [joowani/python-arango#144]
Certainly functions like `insert_many()` and `import_bulk()` will happily function on an EdgeCollection or a VertexCollection, so it seems unexpected that these methods are not available when working on either collection type.

I don't see anything in the ArangoDB documentation that specifically treats EdgeCollections and VertexCollections any different to a StandardCollection, other than the presence of `_from` and `_to` attributes for the edges, so I would have thought it reasonable that these classes can utilise methods defined only in StandardCollection.

**Comment by joowani** [comment]
Hi @nickb937,

Yes you are right. This is one of the techical debts I've been meaning to address. I will look into adding it in the next release.

**Comment by davethejoy** [comment]
Hello Guys, you get +1 on this one.
I am actually interested to get insert_many() in VertexCollection and link_many() in EdgeCollection.
For now I have made a copy of insert_many() as static function, which is working fine. however I still need to implement link_many() from insert_many()

any pointers would be appreciated.
Tx

**Comment by joowani** [comment]
The multi-document methods are now exposed in python-arango version [7.0.0](https://github.com/joowani/python-arango/releases/tag/7.0.0). Please give them a try!

Re @nickb937's question: There IS a difference. The general graph REST APIs that power VertexCollection and EdgeCollection give you the following benefits:

* All modifications are executed in transactions. 
* If a vertex is deleted, all connected edges are also automatically deleted.
* Edge documents are checked against the edge definitions on insert.

Please note that the newly exposed multi-document methods will not give you the safeguards above. This is a limitation of ArangoDB's REST API itself.
