### ISSUE TITLE
arango.exceptions.AQLQueryExecuteError: [HTTP 503][ERR 1496] not a leader

### ISSUE THREAD

**Issue by yangqinj** [joowani/python-arango#150]
Hi, I deploy the ArangoDB (version 3.5.0) with Active Failover mode with three machines and query with the following code (the python-arango is in version 5.4.0) 
``` python
    client = ArangoClient(hosts=["host1:port", "host2:port", "host3:port"])
    db = client.db(name="name", username="user", password="psw", verify=True)

    aql = 'the querry command'

    for x in range(10):
        print("testing", x)
        cursor = db.aql.execute(aql)
        result = [doc for doc in cursor]
        print(result)
```
“host1:port” is the leader and the others are followers. The program raises `arango.exceptions.AQLQueryExecuteError: [HTTP 503][ERR 1496] not a leader` for the second loop:
```
testing 1
Traceback (most recent call last):
  File "D:/Workspace/codehub/kg_python_frame_kgbot/test_arango.py", line 17, in <module>
    cursor = db.aql.execute(aql)
  File "D:\ProgramFiles\Miniconda3\envs\py37\lib\site-packages\arango\aql.py", line 297, in execute
    return self._execute(request, response_handler)
  File "D:\ProgramFiles\Miniconda3\envs\py37\lib\site-packages\arango\api.py", line 66, in _execute
    return self._executor.execute(request, response_handler)
  File "D:\ProgramFiles\Miniconda3\envs\py37\lib\site-packages\arango\executor.py", line 82, in execute
    return response_handler(resp)
  File "D:\ProgramFiles\Miniconda3\envs\py37\lib\site-packages\arango\aql.py", line 294, in response_handler
    raise AQLQueryExecuteError(resp, request)
arango.exceptions.AQLQueryExecuteError: [HTTP 503][ERR 1496] not a leader
```

1. It seems the follower cannot be red which is not accordance with the Active Failover mode.
2. If the leader is failed, `host2:port` becomes the new leader, will the query execute successfully?

**Comment by joowani** [comment]
Hi @yangqinj,

Python-arango will take turns (round-robin or random) sending the request to one host at a time. It seems like this model is not working for your use case. What is your AQL query doing? Only the leader is supposed to be doing write operations.

**Comment by yangqinj** [comment]
Thanks for you reply! I have figured out the problem. For reading from the followers in Active Failover mode, `X-Arango-Allow-Dirty-Read: true` header should be added on each request. Then,  I implemented the following class to add header on each request
```
class ActiveFailoverHttpClient(DefaultHTTPClient):
    """HttpClient for reading from followers by adding header
    {"X-Arango-Allow-Dirty-Read": "true"} for each request."""

    def create_session(self, host):
        session = requests.Session()

        # add request header
        session.headers.update(
            {"X-Arango-Allow-Dirty-Read": "true"}
        )

        return session

```

**Comment by joowani** [comment]
Hi @yangqinj,

Glad you figured it out!
