### ISSUE TITLE
Read timed out. (read timeout=None)

### ISSUE THREAD

**Issue by isaacfi** [joowani/python-arango#154]
python-arango: 6.1.0
ArangoDB: 3.7.6 Community Edition

When I Execute the next query:

```
db = ArangoConnection.db()
periodo_cursor = db.aql.execute('''
            FOR t in Periodo
                RETURN t
            ''')
```

Sometimes I have the next error:

Traceback (most recent call last):
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/flasgger/utils.py", line 255, in wrapper
    return function(*args, **kwargs)
  File "/Users/isaacfi/Code/eneounam.sip/backend/controllers/catalogs_controller.py", line 115, in get_periodos
    lastUpdateDate)
  File "/Users/isaacfi/Code/eneounam.sip/backend/business/catalogs/periodo_business.py", line 41, in get_periodos
    ''', bind_vars=bind_vars)
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/arango/aql.py", line 293, in execute
    return self._execute(request, response_handler)
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/arango/api.py", line 66, in _execute
    return self._executor.execute(request, response_handler)
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/arango/executor.py", line 81, in execute
    resp = self._conn.send_request(request)
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/arango/connection.py", line 250, in send_request
    auth=self._auth
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/arango/http.py", line 109, in send_request
    auth=auth
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/isaacfi/Code/eneounam.sip/backend/venv/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='132.247.114.25', port=8529): Read timed out. (read timeout=None)

This usually happends  when the server is useless for a while (2 mins approx).

This is how I create the arango client:

```
from arango import ArangoClient
from arango.database import StandardDatabase
from settings import ARANGO_DB, ARANGO_HOSTS, ARANGO_PASSWORD, ARANGO_USER


class ArangoConnection:

    _db: StandardDatabase = None

    @staticmethod
    def db() -> StandardDatabase:
        """Connection to SIP

        :return: Arango database connection to SIP
        :rtype: StandardDatabase
        """
        if ArangoConnection._db is None:
            arango_client = ArangoClient(hosts=ARANGO_HOSTS)
            ArangoConnection._db = arango_client.db(
                ARANGO_DB, ARANGO_USER, ARANGO_PASSWORD)
        return ArangoConnection._db
```

BR.

**Comment by joowani** [comment]
Hi @isaacfi,

What do you mean by "when the server is useless". Are you saying this exception is raised when the server still is booting up?

**Comment by isaacfi** [comment]
Hi @joowani,

I mean that this happends when the server (backend/api) doesn't receive requests for a while. Is when the server is up but is not used by the front end application. I read in stackoverflow that maybe is related with the keep-alive-timeout parameter, but I'm not sure.

[Cursor Timeout](https://stackoverflow.com/questions/27304963/arangodb-cursor-timeout)
[Http Keep Alive Timeout](https://www.arangodb.com/docs/stable/programs-arangod-http.html)

BR.

**Comment by joowani** [comment]
Hi @isaacfi,

Python-arango uses [requests](https://requests.readthedocs.io/en/master/) and [sessions](https://requests.readthedocs.io/en/master/api/#request-sessions) with default settings under the hood. 

You can refer to this [page](https://python-driver-for-arangodb.readthedocs.io/en/master/http.html) to see how you can customize the behavior of requests. For example you can debug your issue by disabling keep alive like this:

```python
s = requests.session()
s.config['keep_alive'] = False
```

**Comment by isaacfi** [comment]
Hi @joowani 

The issue still appears only in development mode when I run my flask application. But you gave me an idea to manage the sessions with the custom http client and I may fix the problem.

Thank you

**Comment by isaacfi** [comment]
I was able to solve the issue setting up the session and requests as follow:

```
import logging
from typing import Text, Union

from arango.http import HTTPClient
from arango.response import Response
from requests import Session
from requests.adapters import HTTPAdapter
from settings import (ARANGO_CONNECT_TIMEOUT, ARANGO_HOSTS, ARANGO_MAX_TRIES,
                      ARANGO_READ_TIMEOUT)


class ArangoHttpClient(HTTPClient):

    def create_session(self, host):
        session = Session()

        adapter = HTTPAdapter(max_retries=int(ARANGO_MAX_TRIES))
        if ARANGO_HOSTS.startswith('http://'):
            session.mount('http://', adapter)
        if ARANGO_HOSTS.startswith('https://'):
            session.mount('https://', adapter)
        return session

    def send_request(self,
                     session: Session,
                     method: str,
                     url: Union[str, bytes, Text],
                     params=None,
                     data=None,
                     headers=None,
                     auth=None):
        response = session.request(
            method=method,
            url=url,
            params=params,
            data=data,
            headers=headers,
            auth=auth,
            timeout=(float(ARANGO_CONNECT_TIMEOUT), float(ARANGO_READ_TIMEOUT))
        )

        return Response(
            method=response.request.method,
            url=response.url,
            headers=response.headers,
            status_code=response.status_code,
            status_text=response.reason,
            raw_body=response.text,
        )

```

Where the setting values are:

ARANGO_HOSTS=http://localhost...
ARANGO_CONNECT_TIMEOUT=30
ARANGO_READ_TIMEOUT=60
ARANGO_MAX_TRIES=5

BR.
