### ISSUE TITLE
Automatic retries

### ISSUE THREAD

**Issue by vgasiunas** [joowani/python-arango#155]
Implement automatic retries for all kinds of database requests. Short downtimes due to single node failures or cluster maintenance operations (shard rebalancing, rolling upgrades, etc.) should be transparent to the application. 

The tolerated timeout should be configurable over connection parameters. A database request should be retried until it succeeds or the timeout is reached.

**Comment by rashtao** [comment]
Please consider that it is not always possible to determine whether retrying a request is safe or not at the driver level, since you could produce unwanted effects on the server-side, eg. executing the request multiple times.

Also consider that some ArangoDB endpoints do not fully honor the HTTP specification with respect to idempotency (https://tools.ietf.org/html/rfc7231#section-4.2). According to the HTTP specification GET, HEAD, OPTIONS, TRACE, PUT and DELETE requests should be idempotent, so they must behave according to the following definition:

>    A request method is considered "idempotent" if the intended effect on
>    the server of multiple identical requests with that method is the
>    same as the effect for a single such request.

Unfortunately this does not hold true for all the database endpoints, for example it is violated by `PUT /_api/cursor/{cursor-identifier}`, which reads the next available batch from an AQL cursor.


Therefore, at the current state of ArangoDB server API, I would recommend you retrying GET requests only.

**Comment by joowani** [comment]
Hi @vgasiunas and @rashtao,

Ok sounds good. I'll put retries for GET in the next release.

**Comment by rashtao** [comment]
It is also safe retrying in cases when the request has not been sent to the server at all, eg. in case of exceptions establishing the connection. In such cases it could be meaningful retrying with another host, thus tolerating temporary unavailable servers.
In addition to this, you might periodically poll the cluster endpoints (via `/_api/cluster/endpoints`) to detect new or removed coordinators in case the cluster is scaled up/down.

**Comment by joowani** [comment]
Hi @vgasiunas and @rashtao,

I've added automatic retries in version [7.0.0](https://github.com/joowani/python-arango/releases/tag/7.0.0) with the following defaults: 
```
    def create_session(self, host):
        session = Session()

        # Enable retries.
        retry_strategy = Retry(
            total=3,
            backoff_factor=1,
            status_forcelist=[429, 500, 502, 503, 504],
            method_whitelist=["HEAD", "GET", "OPTIONS"],
        )
        http_adapter = HTTPAdapter(max_retries=retry_strategy)
        session.mount('https://', adapter)
        session.mount('http://', adapter)

        return session
```

Let me know if you think this can be improved.

Polling `/_api/cluster/endpoints` adds quite a bit of complexity, and potentially a need for backwards-incompatible refactor. I also don't like the idea of python-arango making hidden requests behind the scene. I'd be happy to accept a PR if you already have a good idea on how to implement it.

**Comment by rajivsam** [comment]
@joowani , does it make sense to simply define a new custom http client that defines it this way rather than having this as a default for all clients? This is great. Just thinking aloud.

**Comment by joowani** [comment]
@rajivsam Introducing these "sane" defaults (based on [this article](https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/)) seems harmless to me. I don't see any strong reasons for anyone to not want retries, especially in production settings.

**Comment by rajivsam** [comment]
> @rajivsam Introducing these "sane" defaults (based on [this article](https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/)) seems harmless to me. I don't see any strong reasons for anyone to not want retries, especially in production settings.

Makes sense.
Rajiv

**Comment by mooncake4132** [comment]
https://github.com/joowani/python-arango/blob/71285e0552c4f446ecdaa1ec3cffb50e15a96429/arango/http.py#L127
Is the read timeout of 5 seconds a bit too strict? This would fail operations that take longer than 5 seconds. I'm getting timeouts from truncating collections.

**Comment by joowani** [comment]
Hi @mooncake4132,

Yes you are right. I've increased the default timeout to 60 seconds in release 7.1.0. If you need to increase it further, you can always refer to [this page](https://docs.python-arango.com/en/main/http.html) and customize your HTTP client.
