### ISSUE TITLE
How to wait for long process to commit transaction

### ISSUE THREAD

**Issue by isaacfi** [joowani/python-arango#161]
Hi,

Is there any way to wait until a long calculation finished to commit the transaction? Actually I have this exception:

arango.exceptions.TransactionCommitError: [HTTP 400][ERR 1653] transaction was already aborted

BR.

**Comment by joowani** [comment]
Hi @isaacfi,

Bringing this up in ArangoDB's channel will be better as they are more familiar with the inner details of the transaction API.

**Comment by joowani** [comment]
Hi @isaacfi,

Any luck?

**Comment by isaacfi** [comment]
Hi @joowani,

Sorry for my late answer, but I read the transactions limitations in the Arango's documentation, and is not posible to mantain long processes in a transaction, becaus Arango DB only keep alive the transaction for 10 seconds and if the is no interaction with the database, the server drops the transaction. My work around was to move to background the long process with threads to make it independent from the transaction.

BR.

**Comment by joowani** [comment]
I see. Thanks for the update @isaacfi. Sounds like you found your solution so closing this out.
