### ISSUE TITLE
ImportError: cannot import name 'ArangoClient' from 'arango' (unknown location)

### ISSUE THREAD

**Issue by hagfelsh** [joowani/python-arango#162]
Hi!  Your Arango driver is by far the best available and beautifully documented.

I can't seem to use it!  I found two issues that covered this problem.  Both were determined to be namespace conflicts.  I've tried this in a new venv and still no success.  What am I missing?

```
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from arango import ArangoClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ArangoClient' from 'arango' (unknown location)

```

**Comment by joowani** [comment]
Hi @hagfelsh,

Thanks! I'm glad you like python-arango.

After activating your venv, what is the output of `pip list`? Have you installed any other Python drivers for ArangoDB? I know some of them use the same import name `arango`.

**Comment by hagfelsh** [comment]
I've definitely encountered that sort of thing, yep!

Here's the outrageous thing... I wiped the venv **again** and repip'd python-arango.  Lo and behold, the import statement works now.  I can't explain it!  My pip list now looks just like it did when I reported this issue.  Safe to assume that something from a previous arango driver (which did exist for a time until I found yours) remained.

The moral of this story: Pick python-arango from the start and don't install the others!

Anyway here's my pip list:
```
Package           Version
----------------- ---------
beautifulsoup4    4.9.3
certifi           2020.12.5
chardet           4.0.0
dpath             2.0.1
idna              2.10
lxml              4.6.2
mock              4.0.3
nose              1.3.7
numpy             1.20.1
pip               21.0.1
PyJWT             2.0.1
pymongo           3.11.3
python-arango     7.1.0
PyYAML            5.4.1
requests          2.25.1
requests-cache    0.5.2
requests-toolbelt 0.9.1
scalpl            0.4.1
setuptools        54.2.0
setuptools-scm    6.0.1
sndict            0.1.2
soupsieve         2.2
toml              0.10.2
urllib3           1.26.4
```
