### ISSUE TITLE
Pass values without quotes 

### ISSUE THREAD

**Issue by Aggression** [joowani/python-arango#169]
Hi! First of all, I want to say thanks for good documentation. However, I had a question. Perhaps I do not have enough knowledge of Python or I did not notice something in the documentation.

I trying to run query something like that but I can't understand how to pass values `null, true and false` without quotes. The query  works through the arango web interface and results with quotes and without  quotes are different.

`cursor = db.aql.execute(
  'WITH .........  RETURN DF::ASSIGNEES::APITREE(@query)',
  bind_vars={"query": {
    "query": 1234,
    "queryType": "cnid",
    "collection": "Subjects",
    "tree": [
      {
        "id": 10,
        "edge": "CAddress",
        "collection": "Addresses",
        "direction": "OUTBOUND",
        "subTree": [
          {
            "id":4,
            "edge": "CAddress",
            "collection": "Subjects",
            "direction": "INBOUND",
            "subTree": null,
            "countOnly": false,
            "single": false,
            "IsInbound": true
          }]}]}})`

**Comment by joowani** [comment]
Hi @Aggression,

Do `None`, `False`, and `True` not work?
If not, could you please provide me a code snippet with complete example query and also the equivalent input for the web interface so I reproduce the issue? Thank you.
