### ISSUE TITLE
python-arango broken on Colab default environment

### ISSUE THREAD

**Issue by cw00dw0rd** [joowani/python-arango#171]
Recently I discovered that in order to use python-arango with Colab the urllib3 version must be upgraded. Based on the error, I suspect this is due to the implementation of `max_retries` in the python-arango HTTP client. 
Upgrading urllib3 requires restarting the runtime on Colab, which isn't ideal.

Currently, attempting to connect such as is done in [this notebook](https://colab.research.google.com/github/arangodb/interactive_tutorials/blob/master/notebooks/ArangoDB_GOT_Tutorial.ipynb), now fails with this error:
```
/usr/local/lib/python3.7/dist-packages/arango/http.py in create_session(self, host)
     83             backoff_factor=self.BACKOFF_FACTOR,
     84             status_forcelist=[429, 500, 502, 503, 504],
---> 85             allowed_methods=["HEAD", "GET", "OPTIONS"],
     86         )
     87         http_adapter = HTTPAdapter(max_retries=retry_strategy)

TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

While this is a Colab problem, I was curious if there is a solution on the python-arango side that would fix this? As far as I can tell the default Colab environment has urllib3 version 1.24.3 and [comparing](https://github.com/urllib3/urllib3/compare/1.26.5...1.24.3) this to the most recent version the only change with `retry`, that is obvious to me is this:
![image](https://user-images.githubusercontent.com/7775349/121740963-da9fa700-cacb-11eb-88ca-3aa33e55ed07.png)

Any ideas? I suspect implementing a fix will be faster and more likely on the driver side than getting Google to change their default environment.

**Comment by cw00dw0rd** [comment]
After upgrading the Colab environment, it seems to stay up to date, even after closing all sessions and factory resetting runtime. 

It's not ideal for anyone trying out the driver for the first time on Colab but if they only have to do it once and it lasts forever(not sure if this true) that isn't too bad.

**Comment by joowani** [comment]
Hi @cw00dw0rd,

Thank you for the detailed issue. Due to limited resource on my part, python-arango won't be supporting multiple versions of its dependencies. Let me know if you have any other problems. Thanks.
