### ISSUE TITLE
.find() with LIKE operator

### ISSUE THREAD

**Issue by ssemenukha** [joowani/python-arango#172]
Hi!

I need to find documents by several conditions.
And trying to execute code:

`filters = {"state": "published", "public": True, "title": f"LIKE %{phrase}%"}`
`result = db.collection("course").find(filters)`

But get empty result.
Am I doing it wrong?

**Comment by joowani** [comment]
Hi @ssemenukha,

I suggest you try [AQL](https://docs.python-arango.com/en/main/aql.html) instead.
