### ISSUE TITLE
Local connection is slow if you use localhost intead of 127.0.0.1 

### ISSUE THREAD

**Issue by cheve1969** [joowani/python-arango#18]
Just to comment something I detected using other python driver (pyArango).
On windows if you use host="localhost" instead of host="127.0.0.1", connection time is 1 seconds slower.
I don't know why, but this happends with both drivers on windows python-arango and pyArango.

**Comment by joowani** [comment]
Hi cheve1969,

I've changed the default host to `127.0.0.1` in release 3.2.2.

Thanks,
Joohwan
