### ISSUE TITLE
ImportError: cannot import name 'ArangoClient'

### ISSUE THREAD

**Issue by yiyisan** [joowani/python-arango#20]
When i import ArangoClient from arango, It raise 
```
from arango import ArangoClient
Traceback (most recent call last):

  File "<ipython-input-30-fb5a35ea2f64>", line 1, in <module>
    from arango import ArangoClient

ImportError: cannot import name 'ArangoClient'
```
then dir(arango)
```
dir(arango)
Out[29]: 
['Connection',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'aql',
 'c',
 'clients',
 'collection',
 'core',
 'create',
 'cursor',
 'db',
 'document',
 'edge',
 'exceptions',
 'http_clients',
 'index',
 'mixins',
 'response',
 'utils']
```

**Comment by joowani** [comment]
Hi yiyisan,

I believe you've installed the wrong package. I know... there are quite a few out there and it's rather confusing. Make sure you've uninstalled all other arangodb drivers and install **python-arango**:

```
pip install python-arango
```

Thanks,
Joohwan

**Comment by yiyisan** [comment]
@joowani  Thank you for replying!
I'm  surely that installed correct packages
`Requirement already satisfied (use --upgrade to upgrade): python-arango in ./anaconda3/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): six in ./.local/lib/python3.5/site-packages (from python-arango)
Requirement already satisfied (use --upgrade to upgrade): requests in ./anaconda3/lib/python3.5/site-packages (from python-arango)
`

**Comment by yiyisan** [comment]
thei reason is nstalled the  version  from GitHub:  after uninstalling ,it is ok now!
