### ISSUE TITLE
Possibility to use additional AQL functions

### ISSUE THREAD

**Issue by alexandropov** [joowani/python-arango#22]
I wanted to find a document from part of a string which is mostly used in search engines and used by AQL functions, [CONTAINS](https://docs.arangodb.com/3.0/AQL/Functions/String.html#containsl), [LIKE()](https://docs.arangodb.com/3.0/AQL/Functions/String.html#like)

how can this be implemented here?

**Comment by joowani** [comment]
Hi alexandropov,

Are you talking about user-defined AQL functions?
If so, you can check out the python-arango documentation page for managing them [here](http://python-driver-for-arangodb.readthedocs.io/en/master/aql.html#aql-user-functions).
Once you've defined the functions you should be able to call the functions in your AQL statements like [this](http://python-driver-for-arangodb.readthedocs.io/en/master/aql.html#aql-queries).

Let me know if you have other questions.

Thanks,
Joohwan

**Comment by alexandropov** [comment]
thanks, is there a way to blend aql queries with existing predefine functions?

i.e how do i proceed on inserting 

lola = {'_key': 'lola', 'GPA': 3.5, 'first': 'Lola', 'last': 'Martin', 'date','now()'} where now is arangodb conformed date or other related functions?

**Comment by joowani** [comment]
Hi Alexandropov,

For your particular example you can do something like this:

```db.aql.execute("INSERT { _key: 'lola', time: DATE_NOW() } IN students")```

For more details on AQL and AQL syntax please refer to ArangoDB's [documentation](https://docs.arangodb.com/AQL).

Thanks,
Joohwan
