### ISSUE TITLE
any refined collection method?

### ISSUE THREAD

**Issue by alexandropov** [joowani/python-arango#23]
with an example 

`articles = db.collection('articles')`
i had to iterate through 

```
for arts in articles:
  print arts['field_name']
```

is there way to get list of articles with custom refining methods such as limit, count? etc?

the all() methods in class definition fetch all, which will affect performance if we had to load all before filtering what we needed instead of filtering upfront and get what we needed.

**Comment by joowani** [comment]
Hi alexandropov,

If you are trying to filter documents by fields with `limit` you can do something like this:

```articles.find({'field_name': 'foobar'}, limit=10)```

or if you are searching by text something like this:

```articles.find_by_text(key='field_name', query='foo,|bar', limit=10)```

Unfortunately I don't think these methods return the document `count` in the cursor. If you want anything more sophisticated than above you will have to resort to using pure AQL queries via the `db.aql.execute` function. Python-arango is built right on top of the REST API that ArangoDB provides, and is therefore limited by the its constraints. If the API becomes more advanced in the future I will make sure to add the new functionalities to python-arango.

Thanks,
Joohwan
