### ISSUE TITLE
Traverse N edges from start vertex

### ISSUE THREAD

**Issue by alexandropov** [joowani/python-arango#24]
I have posted a question on the 'slack' [community](https://arangodb-community.slack.com/archives/general/p1475135654001230)

I have a let's say 8 edges and i want to select 3 of them starting from the first vertex.
so based on the first vertex collection, i want to list all documents in the right intervals

**Comment by joowani** [comment]
Hi Alexandropov,

Please checkout the documentation for [traversal](http://python-driver-for-arangodb.readthedocs.io/en/master/classes.html#arango.graph.Graph.traverse).
Sounds like what you want is the `max_depth` parameter.

**Comment by joowani** [comment]
Hey Alexandropov,

I haven't heard back from you for a while so I am assuming that you managed to find a way.
Closing this out. Let me know if you have any other questions.

Thanks,
Joohwan

**Comment by alexandropov** [comment]
Yes, it works perfectly, sorry i couldn't get back on time, but i have manage to make it work,
