### ISSUE TITLE
Arango queries execute only once

### ISSUE THREAD

**Issue by afidegnum** [joowani/python-arango#28]
Hi, 

I noticed Arango queries executes only once, is there a way to make the queries persistent or save the queries to be reused?

**Comment by joowani** [comment]
Hi afidegnum,

Are you talking about AQL queries? If so, you can create [AQL user functions](http://python-driver-for-arangodb.readthedocs.io/en/master/aql.html#aql-user-functions) and reuse your logic (the functions will have to be defined in javascript though). You can also create [tasks](http://python-driver-for-arangodb.readthedocs.io/en/master/task.html) to periodically run the same query over and over (again in javascript). Other than that I'm afraid python-arango on its own does not provide a way to persist them.

Thanks,
Joohwan

**Comment by joowani** [comment]
Hi @afidegnum 

I haven't heard back from you for a while so I will be closing this issue. Feel free to reopen if you have any other questions. Thanks!
