### ISSUE TITLE
Can't get document by id on database

### ISSUE THREAD

**Issue by felixlinker** [joowani/python-arango#33]
The database object is missing a function to query a document by its `_id`.

_Or I was just not able to find it but I scanned the class documentation for a couple of times._

**Comment by felixlinker** [comment]
To be complete: It seems like you can't even get a document by `_id` on a collection.

**Comment by joowani** [comment]
Hi @felixlinker 

That's right. The internal REST API provided by ArangoDB (which python-arango builds on top of) does not expose calls to handle documents via their _id field. Could you please let me know what your use case is?  The `_key` and `_rev` fields should be enough to let you handle all documents uniquely.

Thanks,
Joohwan

**Comment by felixlinker** [comment]
I'm trying to validate input. In a method that will add an edge I'd like to check whether the referenced `_from`/`_to` documents are present in the database.

pyArango manages to do do it. But it seems like they just split the `_id`. Of course that is something I could do by myself. (But don't get me wrong I prefer your python-arango over pyArango ;) ). Here is my reference: https://github.com/tariqdaouda/pyArango/blob/master/pyArango/database.py#L118

**Comment by joowani** [comment]
Right I see what you mean. Adding that method to the db class should be trivial. I will take a note of this when working on the next release. Unfortunately, as of right now you will have to do the manual splitting yourself. Thanks for pointing this out and sorry for the inconvenience!

**Comment by felixlinker** [comment]
No worries! There's nothing for me to complain about. You're developing open source therefore I can't demand anything from you. In the worst case I'd stop using your package. But I won't stop using it because it's good!

Thanks anyways for adding it.

**Comment by joowani** [comment]
Hi @felixlinker,

I added a new method `Database.get_document` to cover your use case in the latest release https://github.com/joowani/python-arango/releases/tag/3.5.0. Please check it out and let me know if you have any problems with it. Closing this out. Thanks.
