### ISSUE TITLE
AQLQueryExecuteError: [HTTP 401] Unauthorized while running on web but have success on terminal

### ISSUE THREAD

**Issue by afidegnum** [joowani/python-arango#35]
While using Flash, I tried to run AQL queries on the page, but i ended up with the above error. 

I did run the same credential on a created database which works, 

I have no clue of where the error is coming from

Here is an example of an error, 

`Traceback (most recent call last):
  File "/srv/makeups/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/makeups/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/srv/makeups/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/makeups/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/makeups/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/makeups/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/makeups/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/makeups/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/apps/keyra/core/main/views.py", line 17, in index
    stocks = db.aql.execute("for a in keystock filter a.type == 'folder' limit 100 return a")
  File "/srv/makeups/env/lib/python2.7/site-packages/arango/api.py", line 22, in wrapped_method
    return conn.handle_request(request, handler)
  File "/srv/makeups/env/lib/python2.7/site-packages/arango/connection.py", line 143, in handle_request
    return handler(getattr(self, request.method)(**request.kwargs))
  File "/srv/makeups/env/lib/python2.7/site-packages/arango/aql.py", line 160, in handler
    raise AQLQueryExecuteError(res)
AQLQueryExecuteError: [HTTP 401] Unauthorized
`

**Comment by joowani** [comment]
Hi @afidegnum,

Do you have multiple users with different access privileges in ArangoDB? It could be that you ran create db as user A and the AQL operation with another user B who does not have access to the database.

Joohwan

**Comment by joowani** [comment]
Merging https://github.com/joowani/python-arango/issues/34 into this issue as it seems to be from the same root cause.

**Comment by afidegnum** [comment]
Well, i started with new user and a new database, which didn't work out, I later switched to the root account which didn't worked out either.

I m using Flask Web framework for all the created web applications, the first Application works perfectly using the root account. so i decided to use the same root account for new created database with a new Flask web project that's where the 401 authentication issue is happening

I later come accross [this part of the documentation](https://docs.arangodb.com/3.1/Manual/DataModeling/Databases/) about the problem which can occur when using the same script to switch to different database, which is not my case but suspecting if this could also be the issue. 

I then move all collections to a single database where my previous application resides and created a new graph. this didn't solve the issue but rather encountered the same error. 

I have installed Arangodb on debian jessie Dedicated Server.

**Comment by joowani** [comment]
Just in case, please double check that you have the latest version of python-arango installed. Then while taking a look at this [page](http://python-driver-for-arangodb.readthedocs.io/en/master/database.html), make sure that the database object you create and execute AQL queries with is initialized with the user that has access to the database (i.e. the user that was used to create the database with, a user that was explicitly granted permission, or root). 

If you still get a 401 then it could be something in your app. You can refer to this [page](http://python-driver-for-arangodb.readthedocs.io/en/master/database.html) and try making a AQL HTTP request directly to ArangoDB within your app using the [requests](https://github.com/kennethreitz/requests) client for further debugging.

**Comment by afidegnum** [comment]
HI, 

I have downloaded the latest version of arangodb using the enterprise version,  and upgraded to the latest python-arango.

I have been using root account all along and the same VirtualEnv but it didn't solve the problem. 
Where can i get more descriptive log pointing to the error i m facing?

**Comment by afidegnum** [comment]
Is there a way to close connection to the server ?

**Comment by joowani** [comment]
Hi @afidegnum,

The 401 is coming directly from ArangoDB. All python-arango does is pipe the HTTP error responses back to you (via Python exceptions). So you will have to look at the ArangoDB logs for more details. Is it just the AQL query failing or do all DB api calls result in 401s as well?

Also have you tried making the HTTP request directly from your app? You may have to take this issue to the ArangoDB team: https://github.com/arangodb/arangodb/issues.

**Comment by brianrusso** [comment]
If you can share a snippet of code that replicates your issue we may be
able to help you better.

**Comment by afidegnum** [comment]
ok, the issue is solved. 

i had to create  a new user and password.
