### ISSUE TITLE
Missing parameter "replicationFactor" in create_collection

### ISSUE THREAD

**Issue by tomwolf** [joowani/python-arango#36]
To create a collection inside a cluster with replication we need the parameter  "replicationFactor".
see:
https://docs.arangodb.com/3.1/HTTP/Collection/Creating.html

**Comment by joowani** [comment]
Hi @tomwolf 

Ah look like that parameter was missed. I will add it in the next release. Thanks!

Joohwan

**Comment by joowani** [comment]
Hi @tomwolf 

I've added the parameters `replication_factor` to the `create_collection` method in https://github.com/joowani/python-arango/releases/tag/3.6.0. Closing ticket.

Thanks!
Joohwan
