### ISSUE TITLE
Support for AND or OR in find()?

### ISSUE THREAD

**Issue by zopyx** [joowani/python-arango#40]
More a question than an issue:

is it possible to use the find() API e.g. for searching by

tags=foo OR tags=bar
tags=foo AND tags=bar

e.g. when the document contains tags=["foo", "bar"...]

or is this limited to AQL?

**Comment by joowani** [comment]
Hi @zopyx,

Unfortunately I do not believe this is possible. Also `Collection.find` is one of the "simple query" functions that the ArangoDB team seems to be moving away from in general (which means this function may be deprecated in future versions). So I would recommend you to use AQL for most use cases.

**Comment by zopyx** [comment]
Thought so. I started writing a small AQL query builder that could generated parts of the AQL where clause...work-in-progress

**Comment by joowani** [comment]
Cool please send me a message when you finish it! Closing issue.
