### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by aguilera51284** [joowani/python-arango#41]
You can give a clear example of cache in documents?

:+1:

**Comment by joowani** [comment]
Hi @aguilera51284 

Do you mean AQL queries? Could you please provide more details?

Thanks,
Joohwan

**Comment by aguilera51284** [comment]
Yes in AQL queries :)!

in http://python-driver-for-arangodb.readthedocs.io/en/master/aql.html#aql-query-cache
I do not see any example of how to use it

**Comment by joowani** [comment]
Hi @aguilera51284 

I believe the cache saves the queries you run automatically.
I'm not sure if ArangoDB has an API to let you manage the cache per query-basis.

Thanks,
Joohwan

**Comment by aguilera51284** [comment]
thx @joowani !
Other question
What possibility is there to implement **Sort** in the  function```db.find(filter, offset, limit)``` ??

**Comment by joowani** [comment]
Hi @aguilera51284 

Unfortunately the API endpoint provided by ArangoDB (which the `find` function wraps) does not support sorting. So it is not possible (yet). You would have to use AQL queries instead.

Thanks,
Joohwan

**Comment by joowani** [comment]
Closing this issue as all the questions seem to have been answered.
