### ISSUE TITLE
Collection.import_bulk onDuplicate option

### ISSUE THREAD

**Issue by khamin** [joowani/python-arango#42]
Hello,

ArangoDB [bulk import](https://docs.arangodb.com/3.1/HTTP/BulkImports/#imports-document-values) supports `onDuplicate` (error, update, replace, ignore) option.
Could you please implement this one?

# Implementation Proposal

This gives an forward compatibility and opportunity to pass custom options to endpoint:

* Add `**kw` to `Collection.import_bulk` signature.
* Overwrite `type`, `collection`, `complete` keys with [current Request params](https://github.com/joowani/python-arango/blob/master/arango/collections/standard.py#L915)
* Use resulting dict as Request params.

## Example

```diff
891c891
<     def import_bulk(self, documents, halt_on_error=True, details=True):
---
>     def import_bulk(self, documents, halt_on_error=True, **kwargs):
910a911,914
>         kwargs['type'] = 'array'
>         kwargs['collection'] = self._name
>         kwargs['complete'] = halt_on_error
> 
915,920c919
<             params={
<                 'type': 'array',
<                 'collection': self._name,
<                 'complete': halt_on_error,
<                 'details': details
<             }
---
>             params=kwargs
```

**Comment by joowani** [comment]
Hi @khamin 

Thank you for pointing this out. I've implemented the changes in the latest release https://github.com/joowani/python-arango/releases/tag/3.7.0.

Please refer to the [documentation](http://python-driver-for-arangodb.readthedocs.io/en/master/classes.html?highlight=import_bulk#arango.collections.Collection.import_bulk) for more details on the new parameters!

Best,
Joohwan
