### ISSUE TITLE
verify gives error

### ISSUE THREAD

**Issue by iamhssingh** [joowani/python-arango#43]
Whenever I try to use `.verify()` it gives error. But, on the other hand, I can do queries and all other stuff!

**Comment by joowani** [comment]
Hi @iamhssingh,

Could you please post the stacktrace?

Thanks,
Joohwan

**Comment by iamhssingh** [comment]
@joowani I think I just found the error. `Client.verify()` only works for `root` user!

```
client = arango.ArangoClient(username='testuser', password='testadmin')
client.verify()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/iamhssingh/PycharmProjects/VirtualEnv/lib/python3.4/site-packages/arango/client.py", line 89, in verify
    raise ServerConnectionError(res)
arango.exceptions.ServerConnectionError: [HTTP 401] Unauthorized
```

**Comment by joowani** [comment]
Ah I see. I find it rather strange that root access is required for simply asking for the version. I will keep this in mind and update the documentation. Thanks!

Best,
Joohwan

**Comment by joowani** [comment]
Updated the docstring for the method in https://github.com/joowani/python-arango/commit/da5d30876a226ecdd8e442f39b4c76de411394ea. Closing ticket.

**Comment by iamhssingh** [comment]
@joowani Isn't it wrong? I mean, to check if Arango is working fine and then continue with the stuff what should be done then?

Also, how can I contribute in your project?

**Comment by joowani** [comment]
@iamhssingh Hmm you bring up an interesting point actually. It seems the Java driver ran into a similar issue: https://github.com/arangodb/arangodb-java-driver/issues/114. 

I will need to make some changes to the python-arango API so all the methods in `ArangoClient` are also in `Database` level. So if you are using a non-root user, you would end up having to do something like this:

```
client = arango.ArangoClient(username='user', password='pass')
client.database('database_which_user_has_access_to').verify()
```
I will make the changes in the next release. For now, you can do a workaround something like this:
```
client = arango.ArangoClient(username='user', password='pass')
client.database('database_which_user_has_access_to').properties()  # use this as a ping check for now
```

Unfortunately this is the best we can do as this is the limitation of ArangoDB REST API (python-arango is just a wrapper around it). I will push the next release sometime this weekend.

Thanks,
Joohwan

**Comment by joowani** [comment]
Oh and as for contributing after the next release I will create a development branch, which you can fork and send pull requests to. Thank you for the interest!

**Comment by iamhssingh** [comment]
@joowani Sure. Thanks a lot!

**Comment by joowani** [comment]
Hi @iamhssingh 

I've made the changes in https://github.com/joowani/python-arango/releases/tag/3.8.0. Now you should be able to call `verify()` using another database. I've also made a development branch where you can make pull requests to: https://github.com/joowani/python-arango/tree/dev. Feel free to re-open this issue if you find any problems.

Thanks,
Joohwan
