### ISSUE TITLE
delete_graph doesn't surpport dropCollections oper  in arangod-3.1.25

### ISSUE THREAD

**Issue by bjtudujunlin** [joowani/python-arango#45]
i can't delete the graph together with vectors and edges in this graph because delete_graph has not dropCollections param

**Comment by joowani** [comment]
Hi @bjtudujunlin 

Ah ok. I will take a look and add it in the next release.
Thanks for reporting it.

**Comment by joowani** [comment]
Hi @bjtudujunlin 

The parameter `drop_collections` was added to `Database.delete_graph` in release [3.9.0](https://github.com/joowani/python-arango/releases/tag/3.9.0). Please upgrade **python-arango** to the latest version and let me know if you have any problems!

Thanks,
Joohwan
