### ISSUE TITLE
What are the new improvements?

### ISSUE THREAD

**Issue by afidegnum** [joowani/python-arango#46]
I just got back to this package and i m loving it. I drifted back to sqlalchemy it is wasting all my lifetime, just to implement common models, but fast with arangodb. I will be glad to contribute as well,

**Comment by joowani** [comment]
Hi @afidegnum 

I'm glad that you find python-arango useful and that you want to contribute!

Currently I don't have any features to implement in mind, other than making sure the ArangoDB REST API coverage is as high as possible. For example, going through the changelogs and the API endpoints on ArangoDB documentation and ensuring python-arango covers it completely would be very helpful.

Bringing in the new async features in python 3.5+ would also be area of high interest for the future.

Thanks,
Joohwan
