### ISSUE TITLE
[Question] Is it threadsafe?

### ISSUE THREAD

**Issue by imetallica** [joowani/python-arango#50]
Hi, thanks for the great library! I'm thinking about using ArangoDB on my next project with Flask, and I'm wondering if I can use it safely with `eventlet`? Or if I should create a new client everytime I receive a new request?

Thanks in advance,
I.

**Comment by joowani** [comment]
Hi @imetallica,

Thanks a lot for your interest! Although I have not tested this, I believe it should be compatible with eventlet *for the most part*. By default, python-arango makes API calls using the [requests](https://github.com/requests/requests) library, which eventlet seems to be able to monkey patch.

Assuming that, all python-arango APIs except [Batch Execution](http://python-driver-for-arangodb.readthedocs.io/en/master/batch.html) and [Asynchronous Execution](http://python-driver-for-arangodb.readthedocs.io/en/master/async.html) should be thread-safe.

Best,
Joohwan

**Comment by imetallica** [comment]
Hey @joowani 

Thanks for the response. Well I guess I'll create an `ArangoClient` on each request just to be safe then. :)

Can you add this threadsafe detail on the documentation just as a future reference for people?

**Comment by joowani** [comment]
Hi @imetallica,

Sure it is up to you. And yes I will find some time to look more into the thread safety.

Thanks,
Joohwan

**Comment by joowani** [comment]
Hi @imetallica,

I've merged your PR and updated the documentation in several places regarding thread safety in the latest release. Thank you for your contribution!

Best,
Joohwan
