### ISSUE TITLE
Support for Pregel API(s)

### ISSUE THREAD

**Issue by akki** [joowani/python-arango#52]
Hi

With ArangoDB 3.2, the functionality for using Pregel has been added. I had a [discussion](https://arangodb-community.slack.com/messages/C07NV9NAH/convo/C07NV9NAH-1503032737.000076/) with the admin and they have mentioned about an HTTP endpoint or to have a look at `js/client/modules/@arangodb/pregel.js` but I am not sure how to use them.

Have you already added support for them to your driver. If not, is it possible to add it - if you could shed a bit light on how to use these resources I might be able to send a PR for this integration.

Also, are you there on slack? Tried to ping you there itself but couldn't find you. Thanks.

**Comment by joowani** [comment]
Hi @akki 

I just took a quick look and it seems there is no HTTP REST API support for Pregel yet from ArangoDB.
So unfortunately it is not possible to add it to python-arango. 
And no I am not in the slack channel but you can always email me directly at joohwan.oh@outlook.com.

Best,
Joohwan

**Comment by akki** [comment]
@joowani Is it [`/_api/control_pregel`](https://github.com/arangodb/arangodb/blob/devel/js/client/modules/%40arangodb/pregel.js)? I am not very sure though, but maybe you can understand this.

**Comment by graetzer** [comment]
Hi, just a quick comment:
I did not publicily document the http API for pregel yet, but I am fairly confident that we will not change the current API until we release ArangoDB 3.3
So if you like you can go ahead and implement it. Some example REST calls:

Start a pregel job, is just a POST requiest, the response will contain the pregel `job-id`
```
POST /_api/control_pregel
{"algorithm": "pagerank", "graphName":"abc"}
```

Check the pregel job status
```
GET /_api/control_pregel/<job-id>
{
    "state" : "running",
    "gss" : 12,
    "totalRuntime" : 123.23,
    "aggregators" : {...},
    "sendCount" : 3240364978,
    "receivedCount" : 3240364975
  }
```

Cancel a pregel job
```
DELETE /_api/control_pregel/<job-id>
```

**Comment by joowani** [comment]
Oh I see thanks @graetzer. 
I will take a look and add it to the next release.

Best,
Joohwan

**Comment by joowani** [comment]
Hi @akki  and @graetzer,

I've added the Pregel API to python-arango in the latest [release](https://github.com/joowani/python-arango/releases/tag/3.11.0). Please check it out and feel free to reopen this issue if you see any problems.

Thanks,
Joohwan

**Comment by akki** [comment]
Thanks a lot for the efforts @joowani

**Comment by 27shreya** [comment]
Hi @joowani  @graetzer @akki thank you for your help. But this does not return the pregel result. And also how can I set storage to false to get pregel result in memory.
