### ISSUE TITLE
ConnectionError: BadStatusLine() while invoking collection find() API

### ISSUE THREAD

**Issue by jeeveeyes** [joowani/python-arango#53]
Hi,

I am using python-arango 3.8.0 to connect to ArangoDB 3.1.21 community edition server.

Recently, a ConnectionError was thrown while attempting to do a find() on a collection object (uuid_index) as shown below : 

```
  cursr = self.uuid_index.find({"_key":obj_uuid})
  File "/usr/local/lib/python2.7/site-packages/arango/api.py", line 22, in wrapped_method
    return conn.handle_request(request, handler)
  File "/usr/local/lib/python2.7/site-packages/arango/connection.py", line 165, in handle_request
    return handler(getattr(self, request.method)(**request.kwargs))
  File "/usr/local/lib/python2.7/site-packages/arango/connection.py", line 233, in put
    auth=(self._username, self._password)
  File "/usr/local/lib/python2.7/site-packages/arango/http_clients/default.py", line 105, in put
    verify=self._check_cert
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 528, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

```

I did see earlier closed issues where similar error was reported 

https://github.com/joowani/python-arango/issues/32
https://github.com/joowani/python-arango/issues/29
https://github.com/joowani/python-arango/issues/30

The requests library used by python-arango defaults to no-retries, but does allow tuning it via the urllib3 Retry object as documented here at

https://github.com/requests/requests/blob/master/requests/adapters.py

```
class HTTPAdapter(BaseAdapter):
    """The built-in HTTP Adapter for urllib3.
    Provides a general-case interface for Requests sessions to contact HTTP and
    HTTPS urls by implementing the Transport Adapter interface. This class will
    usually be created by the :class:`Session <Session>` class under the
    covers.
    :param pool_connections: The number of urllib3 connection pools to cache.
    :param pool_maxsize: The maximum number of connections to save in the pool.
    :param max_retries: The maximum number of retries each connection
        should attempt. Note, this applies only to failed DNS lookups, socket
        connections and connection timeouts, never to requests where data has
        made it to the server. By default, Requests does not retry failed
        connections. If you need granular control over the conditions under
        which we retry a request, import urllib3's ``Retry`` class and pass
        that instead.
    :param pool_block: Whether the connection pool should block for connections.
    Usage::
      >>> import requests
      >>> s = requests.Session()
      >>> a = requests.adapters.HTTPAdapter(max_retries=3)
      >>> s.mount('http://', a)
    """
    __attrs__ = ['max_retries', 'config', '_pool_connections', '_pool_maxsize',
                 '_pool_block']

    def __init__(self, pool_connections=DEFAULT_POOLSIZE,
                 pool_maxsize=DEFAULT_POOLSIZE, max_retries=DEFAULT_RETRIES,
                 pool_block=DEFAULT_POOLBLOCK):
```

However,  the session adapter creation is not exposed by python-arango.
Can you please support ways to implement something like the below inside python-arango ?

http://www.coglib.com/~icordasc/blog/2014/12/retries-in-requests.html
Code below is reproduced from above page 

```
from requests.packages.urllib3.util import Retry
from requests.adapters import HTTPAdapter
from requests import Session, exceptions

s = Session()
s.mount('https://', HTTPAdapter(
    max_retries=Retry(total=5, status_forcelist=[500])
    )
)

s.get('https://httpbin.org/status/500')
```

**Comment by joowani** [comment]
Hi @jeeveeyes,

Python-arango actually allows you to override the default HTTP client with your own, but it was never documented properly. I've added a new page in the API documentation [here](http://python-driver-for-arangodb.readthedocs.io/en/master/http.html) explaining how you can leverage this for your usecase. 

P.S. Having to define your own custom HTTP client requires a little bit more work than, say, simply passing in your own session. But it also allows you complete control over your client behaviour. So hopefully you find it useful.

Best,
Joohwan

**Comment by jeeveeyes** [comment]
Hi @joowani,

Thanks for your response and clarification.
I think the sample HTTP client class you have illustrated in the new documentation page fits my requirement. I shall try it and get back.

Regards.

**Comment by joowani** [comment]
Hi @jeeveeyes,

I will be closing this ticket for now. Feel free to reopen if you have any other issues.
