### ISSUE TITLE
Client to an Arango cluster

### ISSUE THREAD

**Issue by elsmorian** [joowani/python-arango#54]
Just wondering if there are already considered best practices connecting a client to an Arango cluster either through python-arango or other that python-arango adopts - I can't find any examples and the client API seems to assume you are only connecting to one end point.

When using a cluster is it more expected that the nodes will be behind a common load balancer for example and requests will be distributed around the cluster, or are people using multiple client objects for a cluster, and sharing the requests between them, within python code?

**Comment by joowani** [comment]
Hi @elsmorian,

You can read the ArangoDB [documentation](https://www.arangodb.com/why-arangodb/cluster/) on clusters for more information:

> ArangoDB clusters consist of a number of ArangoDB instances that talk to each other over the network. These instances play different roles in the cluster, as agents, primary and secondary database servers, and coordinators. 

> When clients communicate with the ArangoDB cluster, they talk to coordinators. These instances coordinate tasks such as executing queries and running Foxx services. They know where the data is stored and optimize where to run user supplied queries. Coordinators remain stateless, so you can easily shut them down and restart as needed.

**Comment by elsmorian** [comment]
Hi @joowani , thanks for the info.

My question is more about, how do you choose which coordinator you use? And if it doesn't matter, do people tend to pick at random through something like a load balancer, or do they randomly pick from a list within their Python application code on connection startup, etc?

**Comment by joowani** [comment]
Hmm I'm not sure. Using something like round-robin sounds reasonable to me but this is just a guess. I think you will have more luck asking the question on ArangoDB github issues page.

**Comment by dothebart** [comment]
You should use a persistent connection, and choose round robin in the driver where to connect.

Alternatively you can set up an http proxy that does this for you.

**Comment by elsmorian** [comment]
@joowani Is this something you would be interested in integrating into the python-arango project?

**Comment by joowani** [comment]
Hi @elsmorian,

Yea for sure! I will add a round robin logic in the next release.
Until then you can write the wrapper in your application (shouldn't be more than a few lines of code I imagine).

I think the original question has been answered so closing this issue for now. Feel free to reopen if you have any more follow-up questions. Thanks.

**Comment by sleto-it** [comment]
@joowani hi, was load balancing then implemented? 

by reading the following page https://python-driver-for-arangodb.readthedocs.io/en/master/specs.html#arangoclient it seems multiple hosts are not supported yet

please could you clarify?

thanks,

**Comment by joowani** [comment]
Hi @sleto-it,

No python-arango does not provide any load balancing yet.
You will have to create multiple ArangoClient instances and juggle them on your own.

**Comment by sleto-it** [comment]
thanks @joowani could we re-open this and change issue type from question to feature request, or open a new ticket to support load balancing natively - in a similar way other arangodb drivers do? wdyt?

many thanks,

**Comment by sleto-it** [comment]
Opened this one https://github.com/joowani/python-arango/issues/94 (as this ticket is closed)
