### ISSUE TITLE
cannot import name ArangoClient

### ISSUE THREAD

**Issue by palooney** [joowani/python-arango#55]
Hello,  I got an error message:

```
No handlers could be found for logger "arango.client"
Traceback (most recent call last):
  File "driver1.py", line 1, in <module>
    from arango import ArangoClient
ImportError: cannot import name ArangoClient
```

when I used ```from arango import ArangoClient```. I know it's extremely strange, but I have totally no idea what happened. Any help will be thankful!

**Comment by joowani** [comment]
Hi @palooney,

There are several ArangoDB drivers on pypi. Are you sure you've installed the right one?
Just in case, try uninstalling all "arango" packages and install python-arango again by running commands like:

```
pip list | grep arango
```

```
pip install python-arango
```

**Comment by palooney** [comment]
Hello joowani, thanks for your reply. I installed both arango (0.2.1) and python-arango (3.11.0), but this problem still occurs. Do you have any suggestion?

**Comment by joowani** [comment]
You will have to uninstall *arango* as there seems to be a namespace conflict between the two packages.

**Comment by palooney** [comment]
That works! Thanks a lot!

**Comment by joowani** [comment]
No problem :)
