### ISSUE TITLE
pypi package does not include license information

### ISSUE THREAD

**Issue by uchuugaka** [joowani/python-arango#57]
> $ pip show python-arango
> Name: python-arango
> Version: 3.11.0
> Summary: Python Driver for ArangoDB
> Home-page: https://github.com/joowani/python-arango
> Author: Joohwan Oh
> Author-email: joohwan.oh@outlook.com
> License: UNKNOWN
> Location: ~/Library/Python/2.7/lib/python/site-packages
> Requires: requests, six

License shows UNKNOWN but the Github repository says MIT license.

**Comment by uchuugaka** [comment]
It might be possible to put it into the setup.cfg file?
https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

or as another named arg for the setup() function in setup.py
`license="MIT"`

**Comment by joowani** [comment]
Hi @uchuugaka,

I've made the fix in the latest release. Thank you for pointing this out!

Cheers,
Joohwan

**Comment by uchuugaka** [comment]
verified!
Thanks!
