### ISSUE TITLE
tests are installed into the python site modules directory, and cause conflicts with other packages that accidentally do the same

### ISSUE THREAD

**Issue by yurivict** [joowani/python-arango#67]
Please do not install tests.
They should be runnable from the build directory.

**Comment by joowani** [comment]
Hi @yurivict,

Thanks for pointing this out! I will take a look and make a fix in the next release.

Joohwan

**Comment by joowani** [comment]
Should be fixed in version [4.0.0](https://github.com/joowani/python-arango/releases/tag/4.0.0). Please note that this version is not backward compatible with 3.x and under.
