### ISSUE TITLE
Collection.import_bulk : halt_on_error defaults to None, not True

### ISSUE THREAD

**Issue by blake-sc** [joowani/python-arango#69]
This was a nasty gotcha: in the documentation for import_bulk it says "halt_on_error" defaults to True, in fact it defaults to None meaning that import_bulk by default silently ignores errors.

I believe it would be best if it actually defaults to True, but in any case the documentation should not be contradictory.

**Comment by joowani** [comment]
Hi @blake-sc,

Thanks for the bug report. Yes I agree and I will make sure to switch None to True in the next release, which should be a few weeks away.

Best,
Joohwan

**Comment by joowani** [comment]
Fixed in version [4.0.0](https://github.com/joowani/python-arango/releases/tag/4.0.0). Please note that this version is not backward compatible with 3.x and under.
