### ISSUE TITLE
No exception when creating an ArangoClient on an Arango server that is not started

### ISSUE THREAD

**Issue by aringot** [joowani/python-arango#72]
Hello,

Shouldn't we get an exception when trying to create an ArangoClient on an Arango server that is not started ?

If my server is not started I get exceptions when I first try to use the ArangoClient object, which is a bit too late... And I am not sure what to catch.

Here is the stacktrace:
` HTTPConnectionPool(host='localhost', port=8529): Max retries exceeded with url: /_db/xxx/_api/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000222009C9E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))`

Thanks in advance !

**Comment by joowani** [comment]
Hi @aringot,

Yea the client does not automatically check the connection. You can use [this flag](https://github.com/joowani/python-arango/blob/master/arango/client.py#L27) if you want an error raised on initialization.

Also, there is going to be a new version of python-arango 4.0.0 released in the coming weeks, with backward compatibility breaking changes. The flag will probably be renamed to something like "verify_connection".

Best,
Joohwan

**Comment by aringot** [comment]
Hi @joowani, I use the verify function from Database, the problem is that you do not catch the Exception that happens when trying to connect to a server that is not started... (your ServerConnectionError is never raised)

**Comment by joowani** [comment]
Are you setting the verify flag to True (it defaults to False)? This is a flag provided by ArangoClient init function (different from Database.verify method). Whether this flag should be True by default is up for discussion I guess.

**Comment by aringot** [comment]
No, the verify flag only works for the root user (and I do not want to use it), but when the flag is True it only calls the verify method, and its code seems to be the same as in Database.verify so I would expect it to give the same result.

**Comment by joowani** [comment]
Ah I see what you mean. Yes the connection check is very naive at the moment. It does not catch any client side errors, only server side. I will make sure to account for this in the new version, but I won't be making any more changes to 3.x.x. You will just have to catch the errors yourself in your application code for now. Sorry for the inconvenience.

**Comment by aringot** [comment]
Ok thanks. For now I will catch requests.exceptions.ConnectionError.

How can I receive a notification when you release 4.0.0 ?

**Comment by joowani** [comment]
That's a very good question! I actually don't have anything set up for notifications..... another thing I should probably look into in the future. It would be nice if this was something Github supported. 

I will keep this issue open and let you know when it is released.

**Comment by aringot** [comment]
Okay, thanks !

**Comment by joowani** [comment]
@aringot Python-arango version [4.0.0](https://github.com/joowani/python-arango/releases/tag/4.0.0) is now out! The new `ArangoClient.db` method should now ping the server and allow you to test the connection as you connect to a database. Please note that 4.0.0 is not backward compatible and you will need to change your code per spec when upgrading. Thanks.

**Comment by aringot** [comment]
@joowani , thanks for the notification, I upgraded to 4.0.0 and made the necessary changes to my code... But the lack of Exception handling is still here.

This time I put the full stack trace, hope it helps !

````Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 166, in connect
    conn = self._new_conn()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000145A1DB2C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8529): Max retries exceeded with url: /_db/ForTunesV0_1/_api/collection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145A1DB2C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 172, in 
  File "C:\Development\***", line 16, in db
    db.ping()
  File "C:\ProgramData\Anaconda3\lib\site-packages\arango\database.py", line 378, in ping
    return self._execute(request, response_handler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\arango\api.py", line 58, in _execute
    return self._executor.execute(request, response_handler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\arango\executor.py", line 80, in execute
    response = self._conn.send_request(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\arango\connection.py", line 71, in send_request
    auth=self._auth,
  File "C:\ProgramData\Anaconda3\lib\site-packages\arango\http.py", line 83, in send_request
    auth=auth,
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8529): Max retries exceeded with url: /_db/ForTunesV0_1/_api/collection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145A1DB2C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))`

**Comment by hamzahalabi** [comment]
@aringot This post is old I'm not sure if you've figured how to handle this exception but I'm facing the same problem you've mentioned and can't find a way to handle that exception as well. 
In my case I faced this error when I was trying to dockerize a .py script of mine that calls ArangoDB, I have a container that contains my .py script and another container that contains an ArangoDB instance. However, I'm getting this error since my .py arango call is failing to find a started server. I'm trying to figure out how to make my .py container call the arangodb container

**Comment by aringot** [comment]
@hamzahalabi as far as I remember I caught the HTTP exception. Unfortunately I do not have access to this code anymore to check.

If both of your containers are running I would except that the py script can reach the arango db over internet. If you wanted it local then you probably want the DB and script in the same container.
