### ISSUE TITLE
Batch upsert?

### ISSUE THREAD

**Issue by wshayes** [joowani/python-arango#73]
I'm trying to figure out how to do an insert or replace using batch mode.  Is that possible?

batch.collection(collection_name).insert(doc)  # won't replace
batch.collection(collection_name).replace(doc)  # won't insert new doc

Is there something that will provide upsert functionality for batch?

**Comment by joowani** [comment]
Hi @wshayes,

Unfortunately none that I know of. It seems ArangoDB doesn't support upsert. So you will have to query first (with `Collection.get_many` for example).

**Comment by wshayes** [comment]
Thanks for checking and thank you for making this client. It is really nice and well designed.

**Comment by joowani** [comment]
Thank you for using it @wshayes!
