### ISSUE TITLE
Adding properties provided for cursor API

### ISSUE THREAD

**Issue by akki** [joowani/python-arango#75]
Hi

Is it possible to add the properties offered by [ArangoDB's cursor API](https://docs.arangodb.com/3.3/HTTP/AqlQueryCursor/AccessingCursors.html) to python-arango's cursor interface?
From what I understand a PUT request is [already being made](https://docs.arangodb.com/3.3/HTTP/AqlQueryCursor/AccessingCursors.html), so would adding a request payload solve this?

I am particularly interested in the `ttl` option - this would allow me to keep the cursor connection live for a longer time (than the default) because I have queries in my application which have high response time.

I might be able to implement the feature if you could hint me in the right direction.

**Comment by joowani** [comment]
Hi @akki,

I believe what you are asking for is already implemented in python-arango.
Did you mean [this](http://python-driver-for-arangodb.readthedocs.io/en/master/specs.html#arango.aql.AQL.execute)?

**Comment by akki** [comment]
Hi @joowani 

Yeah, [that's](http://python-driver-for-arangodb.readthedocs.io/en/master/specs.html#arango.aql.AQL.execute) it. I think I looked up only in the cursor API's [documentation](http://python-driver-for-arangodb.readthedocs.io/en/master/specs.html#cursor) and [code](https://github.com/joowani/python-arango/blob/master/arango/cursor.py), hence couldn't find it. I reckon that this is implemented under the `aql.execute` function.

Thank you for the great work and apologies for this inconvenience.

**Comment by joowani** [comment]
No problem @akki!
