### ISSUE TITLE
gevent (greenlets) support for highly concurrent system

### ISSUE THREAD

**Issue by dilipvamsi** [joowani/python-arango#77]
Hi,
I would like to know if the support for gevent is available for creating a highly available, concurrent flask application using greenlets.

Thanks,
Dilip Vamsi

**Comment by joowani** [comment]
Hi @dilipvamsi,

Unfortunately no. In the future, I am planning to work on python-arango-async, a new driver library compatible with asyncio (for Python versions 3.5+ only), but I don't plan on adding support for other async libraries/frameworks.

**Comment by joowani** [comment]
Closing this out. Feel free to reopen if you have any other questions.

**Comment by Darkheir** [comment]
I think that python-arango supports gevent out of the box because it is based on requests and it is supported by gevent.

The most import part is to patch the low level lib as soon as possible so they can become cooperative

```python
from gevent import monkey
monkey.patch_all()
```
