### ISSUE TITLE
Syntax error while installing python-arango

### ISSUE THREAD

**Issue by zopyx** [joowani/python-arango#8]
Python 2.7.10, virtualenv environment:

[ajung@dev1 arango]$ bin/pip install arango
Downloading/unpacking arango
  Downloading arango-0.2.1.tar.gz (343kB): 343kB downloaded
  Running setup.py (path:/home/ajung/src/arango/build/arango/setup.py) egg_info for package arango
    
Downloading/unpacking nose (from arango)
  Downloading nose-1.3.7-py2-none-any.whl (154kB): 154kB downloaded
Downloading/unpacking mock (from arango)
  Downloading mock-1.3.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Downloading/unpacking funcsigs (from mock->arango)
  Downloading funcsigs-0.4-py2.py3-none-any.whl
Downloading/unpacking six>=1.7 (from mock->arango)
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking pbr>=0.11 (from mock->arango)
  Downloading pbr-1.6.0-py2.py3-none-any.whl (87kB): 87kB downloaded
Installing collected packages: arango, nose, mock, funcsigs, six, pbr
  Running setup.py install for arango
    
      File "/home/ajung/src/arango/lib/python2.7/site-packages/arango/async.py", line 12
        return CommandsProxy(obj
                               ^
    SyntaxError: invalid syntax
    
Successfully installed arango nose mock funcsigs six pbr
Cleaning up...

**Comment by joowani** [comment]
You have to run "pip install python-arango"

**Comment by amensouissi** [comment]
Hello,

Python3.4
project$ bi/buildout
.....
Installing pyramid.
Getting distribution for 'arango==0.2.1'.
  File "build/bdist.linux-x86_64/egg/arango/async.py", line 12
    return CommandsProxy(obj
                           ^
SyntaxError: unexpected EOF while parsing

**Comment by joowani** [comment]
Hi amensouissi

I think you've installed the wrong package.
Please install using ``pip install python-arango``
Thanks!

**Comment by amensouissi** [comment]
Thanks!
