### ISSUE TITLE
Python 3.7 support for Python-arango 3.x?

### ISSUE THREAD

**Issue by tammoippen** [joowani/python-arango#80]
Is this desired? With Python 3.7 `async` became a proper keyword, see [PEP-492](https://www.python.org/dev/peps/pep-0492/#deprecation-plans). Hence, [`async.py`](https://github.com/joowani/python-arango/blob/3.12.1/arango/async.py) is not valid under Python3.7 anymore. I would create a PR for this, but there is no target branch. Only `master` and `dev` and I think both are for Python-arango 4.x?

**Comment by joowani** [comment]
Hi @tammoippen,

The async keyword issue has already been resolved in 4.x. Although untested, python-arango 4.x should be compatible with 3.7 (as it is with 3.6). I won't be making further changes to older versions so I recommend you to upgrade to 4.x instead.

**Comment by tammoippen** [comment]
This also requires to upgrade to ArangoDB 3.3+, if I understand correctly?

**Comment by joowani** [comment]
For full compatibility yes. It should also work for 3.1 and 3.2 for the most part but untested.

**Comment by tammoippen** [comment]
Thank you for the info. :+1:
