### ISSUE TITLE
can't insert edge before vertices

### ISSUE THREAD

**Issue by sirpy** [joowani/python-arango#81]
If I try to insert an edge before i insert it's vertices I get an error Document not found.
When I create the same edge using arango shell or the arango import utility I dont get this error.
Is this a check that's being done on python-arango? on arango http protocol?

to reproduce simply create a graph, a vertex collection and an edge collection, try to insert an edge before inserting any vertices

**Comment by joowani** [comment]
Hi @sirpy,

Python-arango doesn't perform any checks for graphs on its own. The error is probably coming directly from ArangoDB's HTTP API.  Perhaps you can try inserting an edge document via a standard collection.

So instead of doing this:
```
client.db('db').graph('graph').edge_collection('edge_collection').insert(edge_document)
```
Try this (untested):
```
client.db('db').collection('edge_collection').insert(edge_document)
```

**Comment by sirpy** [comment]
thanks i'll try
