### ISSUE TITLE
 how to retrieve result of pregel

### ISSUE THREAD

**Issue by chengaofeng1** [joowani/python-arango#85]
I am a newbie and using ArangoDB 3.2.5. I would like to retrieve the result of pregel in ArangoDB by python-arango driver. Since I want to avoid persisting the result, there is an option "store" which  set to false, My codes is below:
`job_id = pregel.create_job(
    graph='collegeGraph',
    algorithm='scc',
    store=False,
    thread_count=1,
    async_mode=False,
    result_field='test_result'
)`
now ,I don't know how to retrieve result of pregel  ,who can help me?

**Comment by joowani** [comment]
Hi @chengaofeng1,

As far as I know, there is no HTTP REST API support for retrieving pregel results (even the other pregel operations are still undocumented but added to python-arango through internal communication with the ArangoDB team).

You will have to go to the arangodb team directly and ask how you can retrieve them. Thanks.
