### ISSUE TITLE
Import raw data like json into database from python

### ISSUE THREAD

**Issue by wxr1997** [joowani/python-arango#86]
Can we use the python-arango org to import json into database?

**Comment by joowani** [comment]
Hi @wxr1997,

Yes you should be able to. You can find plenty of examples on google on how to read JSON files into memory. You can find out how to put them in ArangoDB using python-arango [here](https://github.com/joowani/python-arango).

**Comment by wxr1997** [comment]
Could you tell me which function to import data in json file into Arango database? I cannot find it on formal document(https://python-driver-for-arangodb.readthedocs.io/en/master/index.html). And almost all examples in the document creat collection or vertex by split the raw data into lines. I need a function which can directly use json file and import data into database. Thanks a lot!
