### ISSUE TITLE
Returning entire result set and ignoring the cursor abstraction.

### ISSUE THREAD

**Issue by TZubiri** [joowani/python-arango#89]
Hey, I'm trying to execute a query while ignoring the cursor abstraction, I appreciate the effort that went into its development and the problems that it's trying to solve, but I would really like it if I could just get the entire result set in memory, for now.

I noticed that the default batch size for a query execution is 0. Does that mean that by default the query returns all the results in one batch? If so, then why does the execute query, by default return a cursor?

Thanks.

**Comment by TZubiri** [comment]
For the moment, I am doing:
`result = [x in for x in cursor]`

to presumably load all results into memory.

**Comment by joowani** [comment]
Hi @TZubiri,

The cursor behavior you see is not specific to python-arango. It is built into ArangoDB's HTTP REST API. (python-arango is just a wrapper on top of this API). 

I think it would be strange for a function to behave differently for one specific value of a parameter. What if, for example, the batch size was piped down from the user? Your application code will have to handle batch_size == 0 case differently from others. I would argue that it is bad design for an API/function to not have a consistent behavior/output format.

But I do understand your point. The default batch_size used to be 10 (to avoid blowing up the client side memory on large result sets), but this arbitrary limit caused confusion from users. So I changed the default to 0 (no limit) but left the behavior consistent for reasons explained above. You can see there's a little bit of history as to why things are the way they are now.

And as to your question: yes, the cursor should have the whole data set in one batch by default. There is no need for you iterate through the cursor. You can either just store the cursor itself somewhere in your application memory (it is a very light wrapper object on top of the list) or do ``cursor.batch`` to get the list directly.

**Comment by TZubiri** [comment]
I agree it would be bad design for the function to return two different objects depending on the parameter, the ideal design would be to have a function that returns the list object (this one should be used in tutorials and such), and another that returns the cursor with a mandatory batch_size parameter. This would make the library easier to use for those that don't need the batch functionality. But I understand how BC might complicate this.

cursor.batch seems to be like a viable alternative.

Thanks!

**Comment by TZubiri** [comment]
Also, I understand that this seems to be built into ArangoDB's HTTP REST API, but I imagine the ArangoDB developers would err on the side of exhaustivity rather than ease of use, thereby delegating the ease of use of the interface to the implementation.

In short, it's ok to abstract things away.

**Comment by joowani** [comment]
Yes of course! Abstracting things away for ease of use is the whole point of this library. My goal is to achieve this as simply and elegantly as possible.

There are at least a dozen methods in python-arango (and ArangoDB REST API) that return a cursor. Having to duplicate each one of them to separate out one functionality does not sound like ideal design to me. It may confuse new users who would be forced to juggle between multiple functions, and even lead them to not use cursors/batching at all, which is a bad practice in general!

I'm not sure how you are using python-arango at the moment, but for any real world applications that need to scale against the web, cursors and batching are pretty much mandatory to protect servers from going oom against large data sets. You can see this from other popular database client libraries as well. One good example would be the postgres one, which returns cursors for any N+ row queries. I would even recommend you to review your usage case and see if you can't batch your logic as well (unless its a simple script for one time use).

If I had to change anything with the way python-arango uses cursors, it would be to bring back the default value of batch_size (10 or w/e) to ensure that users are always protected in some form without having to set the parameter themselves. I'm not sure if removing the default value was the best decision. 

Anyway, if you think this library can be improved, feel free to submit a pull request and I will be happy to take a look :)

Thanks.

**Comment by TZubiri** [comment]
Thanks for the response, the postgres example was really helpful. It seems that I will have to implement batching soon as well, I was kind of hoping to keep things simple for the prototype.

If I see something simple I can contribute I'll submit a PR for sure.

Thank you!
