### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by Himan000** [joowani/python-arango#91]
python-arango v4.3.0
ArangoDB v0.13.10, build 38953b0 (V3.4.0)

When running the simple querry all with the method collection.all using a batch size smaller than the actual collection(about 8million+), results in requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)).

Code detail:
 aql = "FOR doc IN section RETURN doc"
 batch_size = 10000
 cursor = db.aql.execute(aql, batch_size=batch_size)

exception detail:
"C:\Program Files\Anaconda3\python.exe" D:/project/python/project_name/project_name_batch_parser/arangodb.py
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Anaconda3\lib\http\client.py", line 1198, in getresponse
    response.begin()
  File "C:\Program Files\Anaconda3\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Anaconda3\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Anaconda3\lib\http\client.py", line 1198, in getresponse
    response.begin()
  File "C:\Program Files\Anaconda3\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Anaconda3\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/project/python/project_name/project_name_batch_parser/arangodb.py", line 246, in <module>
    merge_section_2_candidate()
  File "D:/project/python/project_name/project_name_batch_parser/arangodb.py", line 191, in merge_section_2_candidate
    cursor = db.aql.execute(aql, batch_size=batch_size)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\aql.py", line 304, in execute
    return self._execute(request, response_handler)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\api.py", line 58, in _execute
    return self._executor.execute(request, response_handler)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\executor.py", line 80, in execute
    response = self._conn.send_request(request)
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\connection.py", line 71, in send_request
    auth=self._auth,
  File "C:\Program Files\Anaconda3\lib\site-packages\arango\http.py", line 83, in send_request
    auth=auth,
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

Sometime it's OK by restarting ArangoDB, but most of the time it fail.Could anyone help this case? thanks.

**Comment by joowani** [comment]
Hi @Himan000,

This usually means the server (ArangoDB) is terminating the connection from the client (python-arango) prematurely, in which case there isn't much that can be done from our side. ArangoDB restarts sometimes changing the outcome also suggests that this is indeed a server issue. My wild guess is that the query is taking too long and it is "timing out" on ArangoDB's side.

You may bring this up with the ArangoDB team. Perhaps there is a configuration that can be tweaked on your server or the database. 

A temporary workaround might be to breakdown the query into multiple, smaller (and therefore faster) ones. For example, if your documents have IDs, you can "shard" your query by querying document IDs beginning with certain letter or number each time.

**Comment by Himan000** [comment]
Hi @joowani ,
     Thanks. Breakdowning the query into multiple, smaller (and therefore faster) ones may work. But using query with batch-size and cursor should be OK, because it fetch a batch every time from dbserver, which should be the same as breakdown query.Am I right?

**Comment by joowani** [comment]
Hi @Himan000,

Oops yes you are right. Breaking down the query further would be pointless. Pardon my bad memory. 

From the little research I just did, it seems the [requests session object](http://docs.python-requests.org/en/master/user/advanced/#session-objects) (which python-arango uses under the hood) uses pooling to reuse TCP connections. The ArangoDB server may not like the same connection being open too long .

So what we can try is not use sessions, which would force open a new connection each time. Please take a look at [this page](https://python-driver-for-arangodb.readthedocs.io/en/master/http.html). It shows you how to inject your own custom HTTP clients. And your client could look something like this (untested):

```
import requests

from arango.response import Response
from arango.http import HTTPClient

class NoSessionHTTPClient(HTTPClient):

    def send_request(self,
                     method,
                     url,
                     params=None,
                     data=None,
                     headers=None,
                     auth=None):

        raw_resp = requests.request(
            method=method,
            url=url,
            params=params,
            data=data,
            headers=headers,
            auth=auth,
        )
        return Response(
            method=raw_resp.request.method,
            url=raw_resp.url,
            headers=raw_resp.headers,
            status_code=raw_resp.status_code,
            status_text=raw_resp.reason,
            raw_body=raw_resp.text,
        )
```

Hopefully this lets you iterate a collection regardless of its size. Let me know how it goes.

**Comment by joowani** [comment]
Also please note that above is still a workaround. Best solution would be to fix the issue server side so that connections are never closed early.

**Comment by Himan000** [comment]
OK, I will try custom HTTP clients and update you when I finish. At the same time, I will try to new an issue in ArangoDB official github site. Thanks.

**Comment by jsteemann** [comment]
@Himan000 @joowani : 
A slightly longer description of what may be happening is available here:
https://github.com/arangodb/arangodb/issues/7882#issuecomment-451408698

I think the ideal solution for this problem is to use streaming cursors, which have been introduced in ArangoDB 3.4. 

Streaming cursors will require driver support (basically the driver has to send an `{"options":{"stream":true}}` attribute to the server-side API at POST /_api/cursor.
If that could be added to the driver, I think this should solve the problem.
Thanks!

**Comment by joowani** [comment]
Thanks for looking into it @jsteemann.

I just pushed a new release [4.4.0](https://github.com/joowani/python-arango/releases/tag/4.4.0) with support for the new parameter `stream` in [AQL.execute](https://python-driver-for-arangodb.readthedocs.io/en/master/specs.html#arango.aql.AQL.execute).

@Himan000 please upgrade python-arango and try it out. As for the slow execution speed, you will need to profile it and provide me with more details.

**Comment by jsteemann** [comment]
@joowani : wow, really quick! Thanks a lot!

**Comment by Himan000** [comment]
@joowani Thanka a lot. I will try the new version of python-arango and update you the result later.

**Comment by jsteemann** [comment]
@Himan000 : it looks like the client-side code is retrieving documents in batches, and for each batch it is running a batch update operation.
The input data will be pulled from the collection shard-by-shard. I think therefore it is possible that while processing data from the first shard, the data selection query on the other shards times out. So when finally the data from the first shards is processed completely and the query turns to the data of the second shard, this error will show up. I think the error will only show up after 10 minutes into the data selection query, but not before. Is that correct?
AFAIK this can be prevented by starting (at least) the database servers with the option `--query.registry-ttl <value>`, where `<value>` is a number of seconds. The default is 600 seconds, so queries may time out after that in a cluster. If you can increase that value to an amount you think is reasonable that problem should go away.

**Comment by Himan000** [comment]
Hi @jsteemann，
      It seems that you're correct.  The error will only show up after around 10 minutes. I will to change the option and update you testing result later. Thanks.

**Comment by Himan000** [comment]
Hi @jsteemann ,
I used below command to start arangodb

`nohup arangodb --starter.data-dir=/data/arangodb --server.storage-engine=rocksdb --starter.host=arangodb001 > arango.log 2>&1 &`

when append --query.registry-ttl=36000 to above start command, server can't start and no error log.
when append --query.registry-ttl=36000 in arangod.conf in dbserver, it doesn't take effect.

Where can I set this option?

**Comment by jsteemann** [comment]
When using the arangodb starter, the option becomes `--all.query.registry-ttl=36000` to set it on all servers.

**Comment by Himan000** [comment]
@joowani ,
I have a collection with more than 170million documents in it. When iterate the whole collection with cursor and update them, it can't go on with no error after around 10 hour, no much cpu and RAM was consumed both on ArangoDB server and python-arango program machine. What happen?

_def opt(collection_name, base_column=None):
    try:
        if base_column is not None:
            aql = "FOR doc IN " + collection_name + " filter not has(doc,\"standard_code\") RETURN [doc._key,doc." + base_column + "]"
        else:
            aql = "FOR doc IN " + collection_name + " filter not has(doc,\"standard_code\") RETURN [doc._key]"
        batch_size = 1000000
        db = arangodb.get_db()
        collection = arangodb_delink_graph.get_collection(db, collection_name)
        cursor = db.aql.execute(aql, batch_size=batch_size, ttl=3600000, stream=True, count=True)
        update_beans = []
        for bean in cursor:
            key = bean[0]
            if base_column is None:
                update_bean = {"_key": key, "standard_code": "0"}
            else:
                base_column_value = bean[1]
                if base_column_value is None:
                    update_bean = {"_key": key, "standard_code": "0"}
                else:
                    update_bean = {"_key": key, "standard_code": "1"}
            update_beans.append(update_bean)
            if len(update_beans) == 100000:
                collection.update_many(update_beans, sync=True)
                update_beans = []
                logging.info("done one batch")
        if len(update_beans) > 0:
            collection.update_many(update_beans)
        logging.info("done")
    except Exception as e:
        print(e)_

**Comment by Himan000** [comment]
Hi @joowani ,
I think above problem is a bug from arangodb [https://github.com/arangodb/backlog/issues/510][https://docs.arangodb.com/3.4/Manual/ReleaseNotes/KnownIssues34.html](url)

**Comment by Himan000** [comment]
Hi @joowani ,
But there is another problem, see below code

```
def opt(collection_name, base_column=None):
    logging.info("opt...")
    try:
        if base_column is not None:
            aql = "FOR doc IN " + collection_name + " filter not has(doc,\"standard_code\") limit 10000000 RETURN [doc._key,doc." + base_column + "]"
        else:
            aql = "FOR doc IN " + collection_name + " filter not has(doc,\"standard_code\") limit 10000000 RETURN [doc._key]"
        batch_size = 1000000
        db = arangodb.get_db()
        collection = arangodb.get_collection(db, collection_name)
        has_record = True
        params = {"collection": collection}

        while has_record:
            logging.info("fetching...")
            cursor = db.aql.execute(aql, batch_size=batch_size, ttl=3600000, stream=True, count=True) # it will last a long time here
            logging.info("fetching done")
            update_beans = []
            has_record = False
            all_tasks = []
            counter = 0

            for bean in cursor:
                has_record = True
                key = bean[0]
                if base_column is None:
                    update_bean = {"_key": key, "standard_code": "0"}
                else:
                    base_column_value = bean[1]
                    if base_column_value is None:
                        update_bean = {"_key": key, "standard_code": "0"}
                    else:
                        update_bean = {"_key": key, "standard_code": "1"}
                update_beans.append(update_bean)
                if len(update_beans) == 10000:
                    params["update_beans"] = update_beans
                    if config.is_mutil_thread:
                        all_tasks.append(executor.submit(add_standard_code_single, params))
                        counter += 1
                        if counter == 100:
                            wait(all_tasks, return_when=ALL_COMPLETED)
                            all_tasks = []
                            counter = 0
                    else:
                        add_standard_code_single(params)
                    update_beans = []
                    logging.info("done one batch")
            if len(update_beans) > 0:
                collection.update_many(update_beans)
            if config.is_mutil_thread:
                wait(all_tasks, return_when=ALL_COMPLETED)
        logging.info("done")
    except Exception as e:
        logging.exception(e)
```

when there is not enough 10000000 documents filter by criteria, cursor = db.aql.execute(aql, batch_size=batch_size, ttl=3600000, stream=True, count=True) will last for a long long time and nothing happens. But it's OK when execute the aql in web UI. What's the problem do you think? thanks

**Comment by Himan000** [comment]
Hi @joowani ,
It seems that it's my code problem. _add_standard_code_single_ has some problem and  last a long time. I close this issue.
