### ISSUE TITLE
Natively supported load balancing

### ISSUE THREAD

**Issue by sleto-it** [joowani/python-arango#94]
Opening as spin-off of https://github.com/joowani/python-arango/issues/54

**Comment by joowani** [comment]
Thanks for opening the ticket. I will take a look but no timeline yet.

**Comment by joowani** [comment]
Python-arango version 5.0.0 is now up! This release provides support for multiple hosts with round-robin or random load balancing.

Please note that this version only works with ArangoDB 3.5+ and breaks backwards-compatibility (you will need to update your application code when you upgrade). Please see the [release notes](https://github.com/joowani/python-arango/releases/tag/5.0.0) for details.
