### ISSUE TITLE
DocumentInsertError when executing the second example (insertion into graph)

### ISSUE THREAD

**Issue by zwurgl** [joowani/python-arango#96]
I run the community edition of ArangoDB on Ubuntu 18.04 and the version 4.4.0 of the python-arango module with python3.6. 

When executing the two examples in the README here, the first one is ok (i see the students are inserted in the students collection as expected). But when running the second example, where a graph is to be constructed, I get a DocumentInsertError: Interestingly enough only with the SECOND insert, that of 'Jake Clark' while the first one of 'Anna Smith' is ok and I can see here entry in the students collection afterward... 

No idea where that comes from. I ran into similar issues before when working on my own ArangoDB with the python-arango interface where I also constantly got DocumentInsertErrors "document not found" when inserting into a vertex_collection. I then thought "ok, let's at least successfully run the examples on the github README page and voila, same error. 

Is this a known issue?  For now I have no idea what that could mean that the first (Anna Smith) insert should pass while the second (Jake Clark) does not.

**Comment by joowani** [comment]
Hi @zwurgl,

What is the error message and the error code in the exception?

**Comment by zwurgl** [comment]
Thanks for the quick reply!! 

I have started fresh and need to be more precise: When doing an insert of a vertex for the first time, it works. On a fresh ArangoDB, your code in the REAMDE works ok. Sorry for the confusion. 

When accidentally doing an insert of a vertex again that is already in the DB, the error code below is returned: That is what confused me (why do I get "document not found" when in this case rather the opposite is true: Apparently an error is thrown when a doc had already been inserted in the past. Would it perhaps make sense to return a message that says "DocumentInsertError: document had been inserted before"? 

So in essence: So far it was my error. I need to catch these cases.

Thanks again, Zwurgl

    students.insert({'_key': '01', 'full_name': 'Anna Smith'})
  File "/usr/local/lib/python3.6/dist-packages/arango/collection.py", line 2527, in insert
    return self._execute(request, response_handler)
  File "/usr/local/lib/python3.6/dist-packages/arango/api.py", line 58, in _execute
    return self._executor.execute(request, response_handler)
  File "/usr/local/lib/python3.6/dist-packages/arango/executor.py", line 81, in execute
    return response_handler(response)
  File "/usr/local/lib/python3.6/dist-packages/arango/collection.py", line 2520, in response_handler
    raise DocumentInsertError(resp, request)
arango.exceptions.DocumentInsertError: [HTTP 404][ERR 1202] document not found

**Comment by joowani** [comment]
Hi @zwurgl,

Yes that misleading error is actually a bug on ArangoDB side. You get a "document not found" when in fact you should be getting a duplicate key error. 

Perhaps you are just copy pasting the example too many times? The example assumes that your database is empty with no collection/document names taken.
