### ISSUE TITLE
where is graph function? 

### ISSUE THREAD

**Issue by tianangthang7** [joowani/python-arango#97]
https://docs.arangodb.com/3.0/Manual/Graphs/GeneralGraphs/Functions.html

**Comment by joowani** [comment]
Hi @tianangthang7,

You can try going to the documentation and searching for graphs:
https://python-driver-for-arangodb.readthedocs.io/en/master/graph.html

**Comment by danielapoliveira** [comment]
Hi @joowani,
I would also like to use functions like [paths](https://www.arangodb.com/docs/stable/graphs-general-graphs-functions.html#_paths), [diameter](https://www.arangodb.com/docs/stable/graphs-general-graphs-functions.html#_diameter),... but I didn't get your answer. It doesn't seem like any of those graph functions are implemented. Are there any workarounds or plans to implement them in the driver?

**Comment by joowani** [comment]
Hi @danielapoliveira,

It looks like ArangoDB's REST API (which python-arango is built on top of) does not expose these methods. There is nothing much I can do until they do and document them.

**Comment by danielapoliveira** [comment]
Thanks for the clarification.
I looked at the functions and looks like they are actually just AQL queries. So I just copied the query from the source code and managed to easily get the diameter that way.

**Comment by joowani** [comment]
Ok great @danielapoliveira. Closing.
