### ISSUE TITLE
Bug? Caching issue?  Collection query vs AQL query difference

### ISSUE THREAD

**Issue by wshayes** [joowani/python-arango#98]
I'm getting a weird issue where the collection query using <collection>.get doesn't match the results of the AQL query. I can't find any place in the arangodb setup that would cache a document result nor in the python-arango code. I'm posting this here in case someone has an idea of something else to do.

I'm putting the last check date (start_dt) into a document in the 'pipeline' collection. When I retrieve it using `pipeline_coll.get(store)`, it returns an out of date `start_dt` value which is clearly different from what I'm seeing in the ArangoDB Web UI document view.

After several minutes, the correct value is showing up from the collection.get() document so I know it's a caching issue - I just can't figure out where it's being cached and how to stop it from happening. I'm also concerned that this might be biting me elsewhere (which is why I'm not just simply moving forward with using the AQL version).

    # AQL query to retrieve start_dt (in aql_start_dt variable)
    query = f"""
        FOR doc IN pipeline
            FILTER doc._key == "{store}"
            RETURN doc
    """

    cursor = edgestore_db.aql.execute(query)
    for doc in cursor:
        aql_start_dt = doc["start_dt"]
        break

    # collection.get retrieval of start_dt value
    if pipeline_coll.has(store):
        doc = pipeline_coll.get(store)
        start_dt = doc["start_dt"]
        log.error(
            f"Get last collection date for {store}",
            start_dt=start_dt,
            aql_start_dt=aql_start_dt,
            store=store,
            doc=doc,
        )

Log results:

pipeline          | {
pipeline          |   "@timestamp": "2019-05-02T16:42:34.035650Z",
pipeline          |   "aql_start_dt": "*2019-05-01T13:10:30.853Z*",
pipeline          |   "doc": {
pipeline          |     "_id": "pipeline/nanopubstore",
pipeline          |     "_key": "nanopubstore",
pipeline          |     "_rev": "_YljRGeu--A",
pipeline          |     "start_dt": "*2019-05-01T13:06:30.853Z*"
pipeline          |   },
pipeline          |   "event": "Get last collection date for nanopubstore",
pipeline          |   "file": "/app/utils_mp.py",
pipeline          |   "function": "get_last_collection_date",
pipeline          |   "line": 217,
pipeline          |   "log.level": "error",
pipeline          |   "logger": "utils_mp",
pipeline          |   "start_dt": "*2019-05-01T13:06:30.853Z*",
pipeline          |   "store": "nanopubstore"
pipeline          | }

My arangodb docker instance (docker-compose entry):

  arangodb:
      container_name: arangodb
      image: arangodb:3.4
      command: --log.level info --log.level performance=info --log.level queries=info --log.level requests=warning
      ports:
        - "8529:8529"
      volumes:
        - arangodb_data:/var/lib/arangodb3
      environment:
        - ARANGO_NO_AUTH=1
        # - ARANGO_ROOT_PASSWORD=${BS_ARANGO_PASSWD:?err}
      networks:
        biodati:
      logging:
        driver: "json-file"
        options:
          max-size: "10k"
          max-file: "3"
      healthcheck:
        test: curl -f http://localhost:8529/_api/version || exit 1
      restart: unless-stopped

**Comment by joowani** [comment]
Hi @wshayes,

Sorry for the late response. Have you checked out this [page](https://www.arangodb.com/docs/stable/http/aql-query-cache.html) in ArangoDB documentation? They do have AQL caching. This issue does not seem relevant to python-arango client as it does not have any builtin caching. You may need to take the issue to ArangoDB team.
